### ISSUE TITLE
Check clippy::pedantic lints

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#100]
Activating these lints should improve the quality of code but would necessitate lots of changes amoung our crates. See #91

**Comment by ionut-arm** [comment]
Should make sure that the docs are kept up to date, e.g. any changes happening to "The `BackEndHandler`" in `interfaces_and_dataflow.md` in Parsec book, in terms of naming operations.

**Comment by hug-dev** [comment]
Some of those lints are useful for example when a component name contains its module name ([cf](https://rust-lang.github.io/rust-clippy/master/#pub_enum_variant_names)) but some others generate too much noise ([cf](https://rust-lang.github.io/rust-clippy/master/#must_use_candidate)) and would take long to differentiate between false positives and true positives. Closing this issue for now as this is not an absolute requirement.
It is good to execute from time to time though, locally.
