### ISSUE TITLE
Should we consider integration with Unix security options?

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#118]
Given how limited access control is in typical Unix OSes, clients might be using some other type of access control mechanism for better security.

Should we consider how Parsec would be used with:
* [AppArmor](https://wiki.archlinux.org/index.php/AppArmor)
* [SELinux](https://selinuxproject.org/page/Main_Page)
* chroot jails
* containers

**Comment by hug-dev** [comment]
We are depending **a lot**, maybe too much, on Unix Access control standard system so looking at how to reinforce it would be very good.
Our configuration and mappings files contain secrets/assets that are only protected with Unix privileges.

**Comment by hug-dev** [comment]
We should think stronger about securing this data at rest. Something like [keyring](http://man7.org/linux/man-pages/man7/keyrings.7.html) could help.

**Comment by hug-dev** [comment]
Adding HMAC as a possible option to check for the key info mappings integrity.
