### ISSUE TITLE
Implement configurable exclusion of deprecated primitives

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#119]
As noted in the soon-to-be-merged protobuf contracts, some (combinations of) key attributes that Parsec supports are considered deprecated and should only be used by clients with a clear understanding of the security implications.

Thomas Fossati's suggestion is that the deprecated primitives are rejected by default, but can be enabled through the runtime configuration by admins.

There is still a question about where these checks should be enforced. My suggestions:
* Create and maintain a list of deprecated primitives in `parsec-interface-rs`, along with means of checking whether a request contains any such primitives
* Implement a feature in `parsec-interface-rs` that allows deprecated algorithms and which is not enabled by default; otherwise return an error when encountering one
* Enable the feature in `parsec`, but enforce the check through some other means, somewhere along the request pipeline (most likely in the `BackEndHandler`, before sending the request to the provider)

**Comment by hug-dev** [comment]
I like the idea of deprecated primitives rejected by default.
We could have a trait for example with a method `fn bool is_deprecated(&self)` (to be call on an `OpXXX` or on a `NativeOperation`) to check if the operation contains deprecated parameters or not.
It would be more secure to allow specific deprecated parameters instead of allowing them all!

**Comment by ionut-arm** [comment]
> We could have a trait for example with a method fn bool is_deprecated(&self) (to be call on an OpXXX or on a NativeOperation) to check if the operation contains deprecated parameters or not.

I like the idea, but `is_deprecated` on an operation implies that the operation itself is deprecated. Maybe something like `is_allowed` which would call an `is_deprecated` on the native `KeyAttributes` structure? We'll have to think well where we provide these checks and where we plan to enforce them.

**Comment by hug-dev** [comment]
Right, because in the end all the security parameters are in the key attributes themselves.
