### ISSUE TITLE
Create a Parsec Rust Client

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#127]
Repository name will be `parsec-client-rust`. The Rust client will provide different abstraction layers as modules, the lowest one simply exposing methods for all the operations in the interface with all the parameters.
A large part of the Rust client could be taken from the current test client.

**Comment by ionut-arm** [comment]
If this client is to be used in the future as the base for the test client, it's important that the Rust client exposes all "intermediary" levels of access.
E.g. I believe the core/minimal client functionality would be at operation-level, allowing a user to send an operation by providing all parameters. However, for test we'd need to potentially send malformed requests, or just random bytes, to the socket. This shouldn't be something exposed by any client library inteded for users, though.

**Comment by hug-dev** [comment]
The repo has been created at this address: https://github.com/parallaxsecond/parsec-client-rust

**Comment by ionut-arm** [comment]
Closing this as all issues pertaining to the client are in the repo mentioned by @hug-dev above.
