### ISSUE TITLE
Delete "Provider" suffix out of provider names

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#134]
Following the rule we applied at most places about name repetition, our providers are under the `providers` module but still contain `Provider` in their name: `MbedCryptoProvider`, `TpmProvider` and `Pkcs11Provider`. I think it might be fine to remove the `Provider` part 😃

**Comment by ionut-arm** [comment]
Actually, I was looking at the code structure, it goes like this:
`providers` -> `<type>_provider` -> `<Type>Provider` (e.g. `providers::tpm_provider::TpmProvider`)

I think it'd make more sense if it was:
`providers` -> `<type>` -> `Provider` (so `providers::tpm::Provider`)

**Comment by hug-dev** [comment]
> 
> 
> Actually, I was looking at the code structure, it goes like this:
> `providers` -> `<type>_provider` -> `<Type>Provider` (e.g. `providers::tpm_provider::TpmProvider`)
> 
> I think it'd make more sense if it was:
> `providers` -> `<type>` -> `Provider` (so `providers::tpm::Provider`)

Yes definitely!

**Comment by samwell61** [comment]
I can't close this :sweat_smile:
