### ISSUE TITLE
Make existence of key info consistent with existence of key

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#149]
Currently we have to check, for each return path within provider methods, whether we have maintained consistency between the existence of the key and the existence of the key info stored in the manager. This applies to key generation, import and destruction.

My idea was that at the beginning of these methods we create (for generate/import) or retrieve (for destroy) the key mapping and feed it to a function that does the rest of the processing (all the param checks, calling the method from the interface underneath). The inner method then returns its `Result`, and based on that, before returning from the main provider method, we either keep or destroy the mapping.

**Comment by ionut-arm** [comment]
(The point of this issue is to hopefully prevent problems like #139 )

**Comment by hug-dev** [comment]
That seems like a good idea!
We would do for import/generate:
1. Create the mapping
2. Call the actual operation
3. Destroy the mapping if 2 failed

Could we do something like:
1. Call the actual operation
2. Create the mapping if 1. succeeded

That is very high-level so I am not sure if possible in all providers.

**Comment by ionut-arm** [comment]
> That is very high-level so I am not sure if possible in all providers.

Should be, all providers have some sort of separation between Parsec-specific functionality and the underlying API.
