### ISSUE TITLE
Add more test cases

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#151]
- [x] Add a test making a request to a provider that is not registered, check for `ProviderNotRegistered` error code
- [x] Use a crate that does both hashing and signing/verifying and use it as another client. Both the Parsec client and the Rust one could be used to sign/verify each other computations

**Comment by ionut-arm** [comment]
- [ ] Write an "all providers" test where you go through all possible combinations of crypto provider pairs and: 
* create a key in each of the two providers
* sign a random hash with both keys
* export the public keys
* cross-import the public keys
* cross-verify the signature

**Comment by ionut-arm** [comment]
I'll write down here other ideas I get for tests.

**Comment by ionut-arm** [comment]
Done in #253
