### ISSUE TITLE
Verify which dependencies can/should be updated

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#158]
Before releasing for production we should review our dependencies and check which ones could or should be updated. We should also check for vulnerabilities in any such dependencies with [`cargo-audit`](https://crates.io/crates/cargo-audit).

**Comment by hug-dev** [comment]
I am updating all dependencies in all of our repos and then checking them with `cargo audit`.

**Comment by hug-dev** [comment]
We need to apply the following on each repository:
* remove the license information of crates we use in the `README.md`
* execute `cargo audit`
* execute `cargo udeps`
* execute `cargo upgrade`
* add a nightly workflow with `udeps` and `audit` in it
* bump, tag and publish a new version

For these crates in the following order:
* `rust-psa-crypto`: parallaxsecond/rust-psa-crypto#61 needed before versioning
* `parsec-interface-rs`
* `parsec-client-rust`
* `parsec-se-driver`
* `parsec-tool`
* `rust-tss-esapi`: parallaxsecond/rust-tss-esapi#124 needed before versioning
* `parsec`: a few more PR will be needed before versioning
