### ISSUE TITLE
Add release-build tests to CI

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#163]
Currently PARSEC is only tested in the default, debug version. We should add Github Actions job to run nightly and perform our usual tests, but on a release build.

We should also perform, as part of the same test, some other build checks like we do for the TSS crate - verify that it builds with a "legacy" compiler version and that it builds with the nightly version. This way we'd be warned about potential issues - both for regressions and for future linting errors.

**Comment by hug-dev** [comment]
Agree that we should test compilation on a release build.
Concerning compiler versions, we decided on the community channel to support a set of OSes/Linux distribution and to make sure that our projects compile on the latest version of Rust available in those platforms.

**Comment by hug-dev** [comment]
To be done with #408
