### ISSUE TITLE
Add an option to pass a path to a build-config file 

### ISSUE THREAD

**Issue by MaximAxelrod** [parallaxsecond/parsec#174]
VAS client team would like to get an option to pass a build-time configuration file to the `cargo build` command. We need this for passing build configuration file with GCC c-toolchain as a default.

**Comment by ionut-arm** [comment]
Apart from adding this configuration value, we should also move all the contents of `main()` in `build.rs` into the `if cfg!(feature = "mbed-crypto-provider")`, as the value computed before that all feed into building the Mbed provider

**Comment by hug-dev** [comment]
The build config file has been removed.
