### ISSUE TITLE
Auto create `/tmp/parsec` with correct permissions on startup

### ISSUE THREAD

**Issue by sbailey-arm** [parallaxsecond/parsec#195]
Would it be feasible to have Parsec create the `/tmp/parsec` directory when it starts, if it doesn't already exist?

If the user that Parsec runs as is already part of `parsec-clients`, then I think it should just need to execute:
```shell
mkdir /tmp/parsec
chown :parsec-clients /tmp/parsec
chmod 750 /tmp/parsec
```

**Comment by hug-dev** [comment]
I agree with the idea, that would facilitate deployments as well.

> chown :parsec-clients /tmp/parsec

Is it required that the current user is part of the `parsec-clients` group to execute that?

I can add more, out of my head:
* if the folder exists, we could make the same checks as the client is doing
* we could check that the current user is `parsec`
* we could check that the `parsec-clients` group exists
* we should have all of those checks activated by default, but be able to disable them with a feature, like in the client (and under testing)

That way, the only action needed by the admin would be to create the `parsec-clients` group.

**Comment by ionut-arm** [comment]
> we should have all of those checks activated by default, but be able to disable them with a feature, like in the client (and under testing)

we should also have tests where we have it active and we run parsec from different users in a container :)

**Comment by hug-dev** [comment]
Done by #205
