### ISSUE TITLE
Investigate the usefulness of an async pipeline

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#209]
Parsec currently works in an "old style" way with only the Unix domain socket listener having some degree of non-blocking'ness. The emerging trend (displayed by `tokio`, for example) is to make asynchronous calls truly async.

This could be a change mainly in the IO area, in dealing with the frontend of the service and how we communicate over IPC channels, but it could also look at the provider interface.

The task here is just to investigate what the changes and tradeoffs would be.

**Comment by hug-dev** [comment]
I think the important point is that the `Listen` trait must be async. It's currently the case for us as we set the socket non-blocking.
Maybe having slow methods be async would be good? For example fetching the mappings?
