### ISSUE TITLE
Configurable conditions where TPM will accept to sign message

### ISSUE THREAD

**Issue by leo-lb** [parallaxsecond/parsec#222]
Hello!

Interesting project! I have a question about a particular use case, could a TPM be configured to accept signing a message only in particular conditions? Such as, during the UEFI Secure Boot process, before executing unsigned userland applications etc. the TPM would sign a message once for an on-boot service (running as part of a signed initramfs for example), once that is done it wouldnt accept to sign any message again until next reboot. Is that possible to do with a TPM, if so, how? Can I do it helped by PARSEC? The idea basically is to allow an on-boot service to authenticate to a remote service while not storing any sensitive information on the machine in clear that unsigned userland applications (root or non-root) could steal and re-use to also authenticate to that remote service and do undesired things against it. I must ensure that only that on-boot service can authenticate against the remote service but it has to work unattended so I was thinking TPM could help.

Thank you!

**Comment by hug-dev** [comment]
Hello 👋 

Thanks for your question. I am no expert regarding TPM so maybe @ionut-arm or @Superhepper can provide more insight regarding TPM functionality.

Concerning Parsec, what I can say is that Parsec itself is a user land application and hence needs a fully booted operating system to work (it uses operating systems primitives).

> allow an on-boot service to authenticate to a remote service while not storing any sensitive information on the machine in clear that unsigned userland applications (root or non-root) could steal and re-use

If that "on-boot" service was also another userland application, Parsec's model is to isolate an application's keys from all other applications so this service should be the only one being able to access the signing key used for authentication.

However you mention "root or non-root" -> that might be problematic as an assumption of Parsec Threat Model is that the applications that use Parsec do not have root privilege. Parsec uses OS access control to maintain some security properties of various components and having one non-trusted application with root privilege might break its security 😞 

Hope that helps at least a little and I hope we can provide more information to you.

**Comment by leo-lb** [comment]
Hello!
Thanks @hug-dev for your answer.

> Concerning Parsec, what I can say is that Parsec itself is a user land application and hence needs a fully booted operating system to work (it uses operating systems primitives).

At initramfs stage Linux is running so that should be sufficient?

> However you mention "root or non-root" -> that might be problematic as an assumption of Parsec Threat Model is that the applications that use Parsec do not have root privilege. Parsec uses OS access control to maintain some security properties of various components and having one non-trusted application with root privilege might break its security 😞

The TPM would need to accept signing a message only once per boot, the machine could only boot onto the signed UEFI boot application (like the ones dracut can generate with Linux kernel, its command line and initramfs embedded), this way we can request this signature from the TPM during boot *all the time* so that later programs running after initramfs cannot request it. The TPM will have to reject any second request to sign a message until next boot. This way it should not matter if applications are root or non-root, the hardware TPM would refuse and there would be no copies of that sensitive data in memory either. I hope that is clearer and that's the functionality I would be looking for! I understand Parsec depends on user/root isolation for some of it's tasks.

Thank you!

**Comment by Superhepper** [comment]
Hrrm. I guess it would be possible. If you can be sure what the values of certain PCR registers at a certain time are known to you then you can use those values as a policy for authentication for using the key that you sign with. And then when you are done you could extend the some of the PCR values in the policy and then it would no longer be possible to sign anything.

**Comment by leo-lb** [comment]
> Hrrm. I guess it would be possible. If you can be sure what the values of certain PCR registers at a certain time are known to you then you can use those values as a policy for authentication for using the key that you sign with. And then when you are done you could extend the some of the PCR values in the policy and then it would no longer be possible to sign anything.

@Superhepper That sounds interesting! Can this be reliable and portable? How would PCR registers be reset in some way for next boot?

**Comment by hug-dev** [comment]
If your use-case can be implemented using some features of the TPM, it might make sense to see if those are available in our [`tss-esapi`](https://github.com/parallaxsecond/rust-tss-esapi) crate. If not let's implement there what you need!

Once there we can see if building an abstraction for it in Parsec would make sense.

**Comment by Superhepper** [comment]
Here is a good [link](https://link.springer.com/chapter/10.1007/978-1-4302-6584-9_12) were PCR are described in greater detail.

No, it would not be very portable. Because the values of PCR registers will vary depending on what machine/hardware/os e.t.c. you will be running on.

**Comment by hug-dev** [comment]
Closing this for now but feel free to open one in the [`tss-esapi`](https://github.com/parallaxsecond/rust-tss-esapi) crate to add support for what you need 💯
