### ISSUE TITLE
Investigate and define the work required for compatibility with Arm Firmware Framework for Armv8-A (FF-A)

### ISSUE THREAD

**Issue by paulhowardarm** [parallaxsecond/parsec#247]
### Summary
Arm Firmware Framework for Armv8-A (FF-A) will make it possible to run PSA services (crypto, storage, attestation) as S-EL0 partitions in OP-TEE. These services would make a suitable back-end for Parsec. This request is to investigate the work items needed to make Parsec compatible with such an OP-TEE architecture. The output from this work should be a set of well-defined engineering issues allowing the work to be implemented.

### Details
Needs investigation, but likely to include at least the following:

- Specifying how Parsec (as a userspace process) can interact with FF-A partitions for secure services. Such a specification may need to come from FF-A itself, but we will need to work with them to get it agreed.
- Creating a Parsec provider for a PSA Crypto service in OP-TEE. It might make sense to have a minimal provider to begin with, and then raise separate issues to build out its functionality across the various primitives. Perhaps reaching functional parity with existing TPM/PKCS11 providers would be a good milestone. We also need to think about how this provider is architected. Is it a new provider that talks directly to FF-A? Or do we make it possible for the Mbed provider to be "re-routed" to the OP-TEE partition?
- Defining and implementing a test framework. Should we have a CI system based on QEMU images, for instance?
- Book updates

### Dependencies
The main dependency is FF-A itself. We will need to coordinate across the projects, and possibly also across Mbed/PSA.

### Definition of Done
This issue can be moved to "done" once it has been elaborated into a credible set of well-understood issues in this repo and in the other repos for a solution. "Credible" means that they have clear scope and can be estimated.

**Comment by ionut-arm** [comment]
Issues have been created. If major changes occur, another investigation issue will be created.
