### ISSUE TITLE
Assemble a PR checklist for code reviewers

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#258]
The amount of information that we need to be aware of when reviewing a PR is increasing, and given the possibility of breaking the sync between code and documentation in "everyday PRs", it would be good to have a checklist to help with this.

The checklist will be published in the book and will cover:
* Rough areas in the book where we should check after some specific types of changes
* Guidelines to follow for the code, either to have idiomatic Rust usage or things that we restrict for ourselves
* General guidelines for our development lifecycle (e.g. commits should be signed, testing should be in place for new functionality)

**Comment by ionut-arm** [comment]
I won't add any points that are fairly obvious - e.g. if we add a new provider, that will certainly involve adding a bunch of stuff in the book and it's a fairly rare occurence.

**Comment by ionut-arm** [comment]
I'll be using this comment as the base for the list and will keep updating it.

## Documentation
If changes are made to the authentication process, [the API overview](https://parallaxsecond.github.io/parsec-book/parsec_client/api_overview.html#authentication-and-sessions), [system architecture](https://parallaxsecond.github.io/parsec-book/parsec_service/system_architecture.html#authentication) and [authenticators](https://parallaxsecond.github.io/parsec-book/parsec_service/authenticators.html) pages should be checked.

If new response codes are added, please review the [status codes page](https://parallaxsecond.github.io/parsec-book/parsec_client/status_codes.html).

If improving support for one of the providers, please check the [service API coverage page](https://parallaxsecond.github.io/parsec-book/parsec_client/operations/service_api_coverage.html).

If large changes are made (including additions or deletions) to the source code structure, please check the [associated page](https://parallaxsecond.github.io/parsec-book/parsec_service/source_code_structure.html).

If changes are made to the placement of service components or utility files, please check the [build and run](https://parallaxsecond.github.io/parsec-book/parsec_service/build_run.html), [secure installation](https://parallaxsecond.github.io/parsec-book/parsec_service/install_parsec_linux.html) pages.

If changes are made to the CLI arguments that need to be passed to run Parsec or its tests, please check the [build and run](https://parallaxsecond.github.io/parsec-book/parsec_service/build_run.html), [secure installation](https://parallaxsecond.github.io/parsec-book/parsec_service/install_parsec_linux.html) and [testing](https://parallaxsecond.github.io/parsec-book/parsec_service/tests/index.html) pages.

If new kinds of tests are added, please check the [testing](https://parallaxsecond.github.io/parsec-book/parsec_service/tests/index.html) page and its child.


## Code-wise:
Follow [Rust API guidelines](https://rust-lang.github.io/api-guidelines/about.html)

Usage of `unwrap`, `expect`, `panic` etc. should be strictly limited to extreme cases and documented properly.

Abstract types should be preferred to generic representations.

Buffers should be zeroed out.

Logs should not contain sensitive data, and the should contain detailed data and error information if configured so.


## [Threat model](https://parallaxsecond.github.io/parsec-book/parsec_security/parsec_threat_model/threat_model.html)
The threat model should be reviewed if:
- Avenues for communication between the service and the rest of the system are created or modified
- Components that deal with authenticating requests are created or modified
- Key namespacing is altered in any way

Special care should also be taken around the bits of code that enforce key policies.

**Comment by hug-dev** [comment]
Thanks!! It looks good, I have a few questions:

> Abstract types should be preferred to generic representations.
What do you mean?

> Buffers should be zeroed out.
Maybe only the ones potentially containing confidential information?

> Usage of unwrap, expect, panic etc. should be strictly limited to extreme cases and documented properly.
I would also add something similar for usage of `unsafe`.

**Comment by ionut-arm** [comment]
> > Abstract types should be preferred to generic representations.
> 
> What do you mean?

Well, that we should use a new type to represent `ApplicationIdentity` instead of just using a `String`, for example. That sort of thing. Will try to make it more explicit.

> 
> > Buffers should be zeroed out.
> 
> Maybe only the ones potentially containing confidential information?

👌 

> 
> > Usage of unwrap, expect, panic etc. should be strictly limited to extreme cases and documented properly.
> 
> I would also add something similar for usage of `unsafe`.

👌

**Comment by hug-dev** [comment]
> Well, that we should use a new type to represent ApplicationIdentity instead of just using a String, for example. That sort of thing. Will try to make it more explicit.

ahh yes agree then!

**Comment by ionut-arm** [comment]
Done here: https://github.com/parallaxsecond/parsec-book/pull/68
