### ISSUE TITLE
Implement configuration

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#26]
Implement a configurator module whose task is to spin up all the system components, given a TOML configuration.

Proposing the following changes:
  * Implement and expose a configuration structure for each component that needs configuring
  * Add said structure to the Builder of the component so that `build()` results in a fully configured module
  * Implement the configurator to pick up a TOML tree structure, parse it into its components and initialise everything in the right order
  * Move system spin-up from main to the configurator, which returns the assembled service ready to be run

Example configuration file:
```

  # PARSEC Service Configuration File

  title = "Parsec Config"

  [listener]
  socket_path = "/tmp/security-daemon-socket"
  socket_timeout = 100

  [[key_id_manager]]
  type = "ondisk"
  name = "on-disk-manager"
  path = "~/.parsec/key_ids/"

  [[provider]]
  type = "mbed-userspace"
  persist_keys = true
  key_id_manager = "on-disk-manager"
  converter = "protobuf"

  [[key_id_manager]]
  type = "mongo"
  name = "mongo-manager"
  address = "127.0.0.1:27017"

  [[provider]]
  type = "pkcs11"
  key_id_manager = "mongo-manager"
  converter = "protobuf"

  [[authenticator]]
  type = "simple"
  default_app_name = "root"

  [[authenticator]]
  type = "jwt"
```

Outstanding questions:
  * What should be the final structure of the config file?
  * Should we move to generating provider ID dynamically?
  * Do we offer the option of setting the provider ID in the configuration?
  * What happens if we have duplicate authenticators? (e.g. two "simple" authenticators with different default app names?)
  * Do we allow defaulting of parameters? (e.g the converter for providers would always be "protobuf", at least for a while)

**Comment by hug-dev** [comment]
### Aside note:
From man page `daemon (7)`, it is said that `systemd` daemons can receive the `SIGHUP` signal to reload their configuration.
I am unsure of the security implications of that but for example, when this signal is received the threads could be joined, the current instances could be dropped and the configurator could be called again. That would be a nice feature 🍸

**Comment by hug-dev** [comment]
As per #50 it would be nice to add a logging option in the configuration that contains a binary option to have or not timestamps in the logs. I think by default it should be disabled.

**Comment by hug-dev** [comment]
Is there more work to do after #51 ?

**Comment by ionut-arm** [comment]
I think the work done so far should cover this issue. If we need to do more things we can raise new issues specific to what other configurables will be added.
