### ISSUE TITLE
Investigate what assets to release

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#279]
When doing proper releases of a crate/repo, we should ideally add the assets that represent that release. The question is - what are those assets? Are they a shallow copy of the repo? Release binaries for some set of platforms?

**Comment by ionut-arm** [comment]
Might be related to #300 as we could release binaries for `aarch64`. Still worth debating which features to be included in the release, for example

**Comment by hug-dev** [comment]
Note that since https://github.com/parallaxsecond/parsec-book/pull/98, the release should contains a small archive of Parsec, a config file and the Parsec tool for the quickstart test. That might be enough for now!

**Comment by hug-dev** [comment]
Closing for now, please re-open if it's still worth to investigate.
