### ISSUE TITLE
rust-spiffe: provide a local validation of the JWT-SVID

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#289]
_This is an issue for the `rust-spiffe` repository when the JWT-SVID feature is merged in._

Currently validation of JWT-SVID tokens is done through the Workload API (`ValidateJWTSVID` operation). However this creates the constraint of trusting the Workload API endpoint: the JWT-SVID is a secret and is a parameter of that call. If an attacker controls that socket then they have access of the authentication values of clients.

The validation could instead be done locally by fetching the trust bundle (the SPIFFE public keys) through the Bundle Endpoint which is authenticated.

**Comment by ionut-arm** [comment]
> The validation could instead be done locally by fetching the trust bundle (the SPIFFE public keys) through the Bundle Endpoint which is authenticated.

From what I understand, this is based on [JWK](https://github.com/spiffe/spiffe/blob/master/standards/SPIFFE_Trust_Domain_and_Bundle.md#4-spiffe-bundle-format) and for authenticating the Bundle Endpoint, there are [two recommended approaches](https://github.com/spiffe/spiffe/blob/master/standards/SPIFFE_Trust_Domain_and_Bundle.md#52-authenticating-the-bundle-endpoint).

The first one uses public CAs to authenticate the keys used in TLS - we'd need to use a TLS implementation and have access to a (local?) set of trusted CA certificates. Maybe we can ask them how they recommend this to be implemented?

The second option uses TLS too, but ultimately relies on an initial trust bundle that is set up "through an offline exchange", so it'd have to be passed/configured by the admin (?)

I'm curious if either of these options is already implemented somewhere in Rust, sounds like something that would be reusable by many other projects that integrate with Spiffe.

**Comment by hug-dev** [comment]
Closing because of the above. If we wanted to add the validation in Parsec, we could use the [`parse_and_validate`](https://docs.rs/spiffe/0.1.1/spiffe/svid/jwt/struct.JwtSvid.html#method.parse_and_validate) method on the new `spiffe` crate that we use.
