### ISSUE TITLE
Service should not start if some components weren't built successfully

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#297]
Currently the service builder is silent about certain errors (i.e. by only logging a warning instead of failing to start). An example of that is attempting to start a service with a duplicate provider (e.g. using two instances of the `MbedCryptoProvider`). Ideally, if anything that is specified in `config.toml` can't be spun up exactly the way it is defined, the service should error out.

This issue is meant to cover three things:
1) identifying where errors can happen during service building
2) making sure that all those errors lead to the service stopping
3) implementing a few config tests to make sure the above is implemented properly

**Comment by hug-dev** [comment]
Is this closed by #298 ?
