### ISSUE TITLE
Investigate cross-compilation to Linux on Aarch64

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#300]
We should provide an easy way and steps how to cross-compile Parsec to the `aarch64-unknown-linux-gnu` target.

See #55 for history.

**Comment by ionut-arm** [comment]
Assigning this to myself since I've been doing some work on this for the Trusted Service provider

**Comment by hug-dev** [comment]
It'd be good to test with `armv7-unknown-linux-gnueabihf` as well (Raspberry Pis).

**Comment by hug-dev** [comment]
For the book: https://github.com/parallaxsecond/parsec-book/issues/90
For the tss crate: https://github.com/parallaxsecond/rust-tss-esapi/issues/204
