### ISSUE TITLE
Investigate testing of Cryptoauthlib provider

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#315]
The cryptoauthlib provider, introduced in #303, cannot be properly tested right now because there seems to be no way to hook the library up to an implementation that would work on the CI. Manual testing can be done offline, but having some means of automatically detecting regressions would be good to have.

This issue is meant for investigation only, and depending on the results, new issues should be created for subsequent work.

There are a few avenues to pursue here:
* trying to find a suitable software solution to serve as a backend for cryptoauthlib
* writing a mock backend for cryptoauthlib
* testing the provider more through unit tests (or, in any case, tests that focus on a smaller code area than E2E)

**Comment by ionut-arm** [comment]
An idea I just had was around making the cryptoauthlib Rust wrapper a multiplexer through features. Then for testing we can turn on a feature which converts and redirects calls to some other software implementation (e.g. Mbed Crypto). We won't actually be testing the backend, but at least we can test the provider - it's not like we expect real-world deployments to use the software TPM or PKCS11 implementations we use for testing either.

**Comment by RobertDrazkowskiGL** [comment]
Yes, I think what is needed to enable CI testing is a software implementation of _CryptoAuthentication Library Rust API_ and rust-cryptoauthlib is probably the best place for this.

**Comment by RobertDrazkowskiGL** [comment]
So I was just hit by this issue in pull request #354. We'll work on it.
When I look into other provider' directories I have an impression that not all operations supported by the provider must be implemented for CI. I mean no Parsec sources will be touched, just rust-cryptoauthlib will implement mocks for "instantiation", maybe one or two operations to be checked (on Parsec side PsaGenerateRandom is my candidate), the other operations may simply return "not supported" from rust-cryptoauthlib, and it should be OK in the short term.
This would reduce the meaning of  label "large"  to a human scale.
Is my plan acceptable?

**Comment by hug-dev** [comment]
> When I look into other providers' directories I have an impression that not all operations supported by the provider must be implemented for CI.

Yes that's correct! The tests often begin with:
```rust
if !client.is_operation_supported(Opcode::PsaRawKeyAgreement) {
    return;
}
```
To check if the default provider (the one being tested) supports the operation. Also, some tests have:
```rust
#[cfg(feature = "tpm-provider")]
```
to not even compile them if they won't be supported by the provider.

I would be ok, in the short-term, to have mocks so that it just checks that it compiles but it's easy to add support later on. I am also thinking that if you return an empty array instead of `SUPPORTED_OPCODES` for `describe` then the client will jump all the tests. Just an idea anyway.

**Comment by RobertDrazkowskiGL** [comment]
> 
> 
> > When I look into other providers' directories I have an impression that not all operations supported by the provider must be implemented for CI.
> 
> Yes that's correct! The tests often begin with:
> 
> ```rust
> if !client.is_operation_supported(Opcode::PsaRawKeyAgreement) {
>     return;
> }
> ```
> 
> To check if the default provider (the one being tested) supports the operation. Also, some tests have:
> 
> ```rust
> #[cfg(feature = "tpm-provider")]
> ```
> 
> to not even compile them if they won't be supported by the provider.
> 
> I would be ok, in the short-term, to have mocks so that it just checks that it compiles but it's easy to add support later on. I am also thinking that if you return an empty array instead of `SUPPORTED_OPCODES` for `describe` then the client will jump all the tests. Just an idea anyway.

Thank you for the hints. We willl start working on it soon and we will see how much we can get.
