### ISSUE TITLE
Investigate calculating test coverage

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#342]
We have a variety of different tests in Parsec, it would be good to know what is our test coverage. That would help us knowing if we need to do more or less.

**Comment by ionut-arm** [comment]
I'm currently looking at [`tarpaulin`](https://crates.io/crates/cargo-tarpaulin) for coverage, trying to see if/how our test framework works with it.

Seems to work by calling it like this:
```
RUST_LOG=info cargo tarpaulin --forward --command build --features="mbed-crypto-provider,direct-authenticator" --run-types bins --timeout 3600 -- -c e2e_tests/provider_cfg/mbed-crypto/config.toml
```
And then running the tests from a separate thread, followed by a `pkill parsec`.

**Comment by ionut-arm** [comment]
It's worth considering whether we want to have the code coverage checks running in the CI and then having the results published to something like [Codecov](https://about.codecov.io/)

**Comment by hug-dev** [comment]
Is it possible to calculate it for *all* of our tests and not just the end to end ones?

> It's worth considering whether we want to have the code coverage checks running in the CI and then having the results published to something like Codecov

Would be nice! Personally I would prefer generating the results nightly to check what is the global coverage status instead of making it a requirement to merge a PR

**Comment by ionut-arm** [comment]
> Is it possible to calculate it for all of our tests and not just the end to end ones?

As in, stress tests, persistency tests etc? I think so, I have a plan for how to do it

> Personally I would prefer generating the results nightly to check what is the global coverage status instead of making it a requirement to merge a PR

Yep, I don't think it's needed per PR, we just need to add it to the nightly stuff

**Comment by hug-dev** [comment]
> As in, stress tests, persistency tests etc? I think so, I have a plan for how to do it

Ah yes those but I was also wondering about unit tests?

**Comment by ionut-arm** [comment]
I'll try and figure that afterwards, currently trying with just integration testing - adding unit tests would be more problematic because it'd have to combine the results from multiple tarpaulin runs

**Comment by ionut-arm** [comment]
I tried to run the service under tarpaulin and then run all the integration tests for every provider, sequentially, but it really didn't like it too much... It was getting a bunch of segfaults, the first ones I saw were due to using `drop(...)` in `main.rs` when reloading the service. I think there were more issues in other parts of the code, but I dropped it - will try with `grcov` which maybe is more straight forward to get working.

**Comment by hug-dev** [comment]
Code coverage can be seen [here](https://codecov.io/gh/parallaxsecond)
