### ISSUE TITLE
Investigate tarpaulin segfaults

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#349]
PKCS11 testing under tarpaulin for code coverage generation has been removed because whenever the service was stopped it triggered a segfault in tarpaulin and the test results would be lost. We're currently excluding the PKCS11 provider from coverage reporting.

**Comment by hug-dev** [comment]
Problem fixed with the PKCS11 provider but same problem with the TS one.

**Comment by ionut-arm** [comment]
Problem doesn't appear with TS provider anymore, see #573
