### ISSUE TITLE
Improve logging message structure

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#36]
Currently our log messages specify the error that occurred, however it would be useful to also include the location in code. 
Example:
Currently: "Failed to read request; status: {}" 
Enhanced: "FrontEndHandler handle_request: Failed to read request; status: {}"

Alternatively, when implementing actual logging, this might be sorted out for us by the logging framework (?)

**Comment by hug-dev** [comment]
`env_logger` put in the code at #48 has the following output:
```
[2019-10-18T15:39:51Z INFO  parsec::providers::mbed_provider] Mbed Provider - Destroy Key
```
Is that what you had in mind?

**Comment by ionut-arm** [comment]
> `env_logger` put in the code at #48 has the following output:
> 
> ```
> [2019-10-18T15:39:51Z INFO  parsec::providers::mbed_provider] Mbed Provider - Destroy Key
> ```
> 
> Is that what you had in mind?

Yes! Though I'm not sure it'd be that helpful to admins, but better than nothing
