### ISSUE TITLE
Design workflow and associated APIs for key attestation in Parsec

### ISSUE THREAD

**Issue by paulhowardarm** [parallaxsecond/parsec#370]
### Summary
Parsec clients should be able to prove that a provisioned key resides in verified hardware. This needs to be introduced while maintaining the abstraction philosophy of Parsec. We need a design for the APIs that should be introduced to support this, and a sketch of the workflow that a client would use to do an attestation.

### Motivation
When a key is provisioned in secure hardware, it is a common requirement (and sometimes a regulatory necessity) for a client to be able to prove cryptographically that the key resides within that hardware, and has not been misappropriated by a MITM or other rogue agent. This is typically done by verifying the key against an external trust authority. This trust authority will have established trust with the device at manufacturing time, by means of a fused private key of some kind. The trust authority can generate a cryptographic challenge for the device, allowing the device to prove that it owns the key material. While this concept is common across the platform ecosystem, the details vary. Sometimes there is direct support within the API, and sometimes it is necessary to orchestrate several API primitives (and read lots of documentation) to bring about this attestation sequence. Parsec can add value here by defining a common API, and doing the required orchestrations of operations within the various providers. The aim would be to create a client experience that is as portable as possible.

### Requirements
Some specific requirements/assumptions for the design:

- The Parsec API needs to be as generic/portable as possible, and needs a credible mapping from the defined opcodes to the underlying APIs of the individual crypto providers.
- The API need not necessarily be based on PSA specifications, because PSA is largely just a set of primitives, and key attestations would probably need to orchestrate across multiple primitives while also bringing in some platform knowledge and config.
- Any new opcodes defined should only use the `Psa` prefix if they directly correspond to a PSA API signature.
- Mappings to crypto providers should be as complete as possible. It would be good to show that we have a credible abstraction, and that it is not heavily skewed towards a particular platform such as TPM. We do not need to nail every detail for every provider. Indeed, in the general case this might not be possible. Attestation is sometimes highly hardware-specific. The PKCS#11 provider, for example, might need to combine various API calls with other intelligence about the platform, possibly coming from manufacturer documentation. In fact, we might need to create a design that allows for multiple different attestation implementations even within a single provider.
- We can assume some client intelligence about how to interact with the external trust authority. For example, it would be reasonable for the API to yield some sort of opaque blob of "endorsement data" (which could be a cert), and to assume that the client will know what to do with it. Parsec client libraries might be able to help out with common verification paths.

### Definition of Done
For this ticket to be complete, there needs to be a design in place for the API opcode contracts (perhaps a book PR) coupled with some documentation on how a client would be expected to use them (eg. sequence diagram). It also has to be shown how these contracts can credibly be mapped to the crypto providers and their corresponding APIs and flows (TPM 2.0, PKCS#11, CryptoAuthLib, Trusted Services). An implementation is not required - it would make sense for implementations to be done as separate tickets, and they could be delivered individually.

**Comment by ionut-arm** [comment]
A proposal for the key attestation workflow can be seen [here](https://drive.google.com/file/d/11jLLv8zN_xRunj9BEkk_L_tj5DiQOtkG/view?usp=sharing) along with a brief dive into some of the backends that we could reasonably expect.

**Comment by ionut-arm** [comment]
Documentation for operations for preparing and then performing key attestation has been merged to the book under https://github.com/parallaxsecond/parsec-book/pull/124

The next step is to propose and merge contracts for said operations.

**Comment by ionut-arm** [comment]
Closing this issue, as the new contracts will be done under https://github.com/parallaxsecond/parsec-operations/issues/33 .
