### ISSUE TITLE
Document clearly how Mbed Crypto provider keys are stored

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#373]
The documentation for what gets stored on disk for the Mbed Crypto provider isn't clear enough, as it could be misunderstood (based on the `store_path` of the `KeyInfoManager`) that the keys are stored along with their mappings.

In reality, the keys are stored locally in the working directory of the process using the Mbed Crypto library. This can be changed at compile time (see [this](https://github.com/ARMmbed/mbedtls/blob/bb86d0c61cb955bddd57fe3d4827b84556103aff/library/psa_its_file.c#L46)) - maybe we could also include this as part of our build, but the main point is that the behaviour should be described more thoroughly *somewhere*, preferably both [in the book](https://parallaxsecond.github.io/parsec-book/parsec_service/providers.html#mbed-crypto-provider) and [in the config file](https://github.com/parallaxsecond/parsec/blob/master/config.toml#L94)

**Comment by hug-dev** [comment]
Related to #53

**Comment by ionut-arm** [comment]
Solved in the two PRs linked above
