### ISSUE TITLE
Make the slot_number field optional

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#375]
The PKCS 11 provider can use the [`get_all_slots`](https://docs.rs/cryptoki/0.1.1/cryptoki/struct.Pkcs11.html#method.get_all_slots) function to use the first slot returned if the `slot_number` field was not given. It will save some trouble to the admin!

**Comment by ionut-arm** [comment]
What was the difference between that one and `get_slots_with_token`?

**Comment by hug-dev** [comment]
oh yeah I think `get_slots_with_token` should be used.
From the documentation:

>  tokenPresent indicates whether the list obtained includes only those slots with a token present

I am not fully sure of the difference between a slot and a token but I think a token is in a slot when there is actually something to use there.

**Comment by Sven-bg** [comment]
Hi @hug-dev, if you want I can work on it.
Thank you

**Comment by hug-dev** [comment]
Sure! Thank you!

**Comment by wiktor-k** [comment]
> I am not fully sure of the difference between a slot and a token but I think a token is in a slot when there is actually something to use there.

Indeed. My understanding is that slot = smartcard reader, token = smartcard in the reader. For general use `get_slots_with_token` is better. `get_all_slots` is useful only when learning about the actual readers (they have some metadata associated too).
