### ISSUE TITLE
Archive for 0.7.0 contains .cargo/ folder

### ISSUE THREAD

**Issue by ggardet** [parallaxsecond/parsec#377]
Archive for `0.7.0` contains `.cargo` folder, but should not. Please drop it for next release.

**Comment by hug-dev** [comment]
Do you mean the crates.io archive that is published? The `.cargo/config` file contains the linker commands to use for cross-compilation. Will cross-compilation work if we remove it?

**Comment by ggardet** [comment]
I meant the source archive.
It broke my build system, but I managed to workaround it, so I guess we could keep it, sorry for the noise.
