### ISSUE TITLE
Setup environment stability test

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#386]
Parsec service testing covers a broad spectrum of use cases and behaviours that we want to continuously verify - the obvious tests that the functionality exposed by the API actually works, stress testing, tests that check configuration changes etc.

However, we do not have any tests that look at stability, at making sure that nothing breaks when replacing a service binary of version x.y.z with one of version x.y+1.z, for example, in an environment that represents some bespoke state.

My initial idea was that we could create another Docker image where, apart from having all the dependencies installed, we also create a number of keys for a number of clients. We then replace the service binary and check that everything still works.

**Comment by hug-dev** [comment]
Let's work on that in #394
