### ISSUE TITLE
Stability: Communication with clients (requests/responses)

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#388]
Definition: Requests and responses must be understood correctly by different versions of the service/clients.
Enforcement: The Wire Protocol is stable by design.

## Enforcement check

As Parsec currently respects the wire protocol, this requirement is already enforced.

One thing to check is if adding new values to enum-like types (for example [`Algorithm`](https://parallaxsecond.github.io/parsec-book/parsec_client/operations/psa_algorithm.html#algorithm-type), [`KeyType`](https://parallaxsecond.github.io/parsec-book/parsec_client/operations/psa_key_attributes.html#keytype-type)) is possible or would need new types and new operations using those types.
For example PSA Crypto `1.0.1` [added](https://armmbed.github.io/mbed-crypto/html/appendix/history.html) a new hash algorithm ([`PSA_ALG_SM3`](https://armmbed.github.io/mbed-crypto/html/api/ops/hashes.html#c.PSA_ALG_SM3)) and a new key type ([`PSA_KEY_TYPE_SM4`](https://armmbed.github.io/mbed-crypto/html/api/keys/types.html#c.PSA_KEY_TYPE_SM4)). Would adding those to our existing contracts be ok?
If we wanted to add those new values, would we have to create new `Algorithm` and `KeyType` types in the contracts (and incidentally new operations for all the current operations that are using those types)?
Should we just say that Parsec is following PSA Crypto `1.0.0`? Should we then maintain a separate `1.0.0` feature on the `psa-crypto` crate, as Parsec uses it directly?

## Testing

As opposed to other stability requirements, this one is more restrictive: all versions of the Parsec service should work with all versions of clients. "Work" is to be defined here as of course a client using an opcode not yet supported in the service will not "work".

Testing should be composed of a various set of operations using different parameters with different versions of the Rust clients against different versions of the Parsec service. Ideally the set of operations should be exhaustive but this is not realisitc. Maybe we could look at re-using the end-to-end tests?

**Comment by hug-dev** [comment]
I did some investigation to check what would happen if we **allowed non-breaking updates to our contracts**.

Because we only support protobuf right now, the investigation was done on the protobuf contracts, but I expect other contract formats to behave in similar ways.

I tried three possibilities, on structures that are shared amoung a lot of operations:
1. Added a new hash variant: `TOUSTE_HASH = 16;`. That is testing adding a new variant to a Protobuf `enum`.
2. Added a new field to the usage flags: `bool touste = 11;`. That is testing adding a new field to a protobuf message.
3. Added a new key type variant: `message TotoType` and `TotoType toto_type = 15;`. That is testing adding a new `oneof` variant.

Those three things cover all non-breaking updates (additions more specifically) to our contracts.

Then I produced serialised test data with and without the changes and tried two things:
1. With the new version (with the new changes), try to deserialize test data from the old version.
2. With the old version, try to deserialize test data from the new version.

# Producing test data

## Without the changes

Test file:
```rust
#[test]
fn touste() {
    use psa_key_attributes::{UsageFlags, KeyType, key_type};
    use psa_algorithm::algorithm::Hash;
    use prost::Message;
    
    let usage_flags = UsageFlags {
        export: true,
        copy: true,
        cache: true,
        encrypt: true,
        decrypt: true,
        sign_message: true,
        verify_message: true,
        sign_hash: true,
        verify_hash: true,
        derive: true,
    };

    let hash = Hash::Sha3512;

    let key_type = KeyType {
        variant: Some(key_type::Variant::Des(key_type::Des { })),
    };

    println!("hash: {:?}", hash as i32);

    let mut buff1 = Vec::new();
    usage_flags.encode(&mut buff1).unwrap();
    println!("usage_flags: {:?}", buff1);

    let mut buff2 = Vec::new();
    key_type.encode(&mut buff2).unwrap();
    println!("key_type: {:?}", buff2);
}
```
That produced:
```
hash: 15
usage_flags: [8, 1, 16, 1, 24, 1, 32, 1, 40, 1, 48, 1, 56, 1, 64, 1, 72, 1, 80, 1]
key_type: [42, 0]
```

## With the changes

Test file:
```rust
#[test]
fn touste() {
    use psa_key_attributes::{UsageFlags, KeyType, key_type};
    use psa_algorithm::algorithm::Hash;
    use prost::Message;
    
    let usage_flags = UsageFlags {
        export: true,
        copy: true,
        cache: true,
        encrypt: true,
        decrypt: true,
        sign_message: true,
        verify_message: true,
        sign_hash: true,
        verify_hash: true,
        derive: true,
        touste: true,
    };

    let hash = Hash::TousteHash;

    let key_type = KeyType {
        variant: Some(key_type::Variant::TotoType(key_type::TotoType { })),
    };

    println!("hash: {:?}", hash as i32);

    let mut buff1 = Vec::new();
    usage_flags.encode(&mut buff1).unwrap();
    println!("usage_flags: {:?}", buff1);

    let mut buff2 = Vec::new();
    key_type.encode(&mut buff2).unwrap();
    println!("key_type: {:?}", buff2);
}
```
That produced:
```
hash: 16
usage_flags: [8, 1, 16, 1, 24, 1, 32, 1, 40, 1, 48, 1, 56, 1, 64, 1, 72, 1, 80, 1, 88, 1]
key_type: [122, 0]
```

# Trying to deserialize test data

## Deserialize old data with new version

Test file:
```rust
// Generate buffers for Hash, KeyType, UsageFlags
#[test]
fn touste() {
    use psa_key_attributes::{UsageFlags, KeyType};
    use psa_algorithm::algorithm::Hash;
    use prost::Message;

    let hash: i32 = 15;
    let usage_flags: Vec<u8> = vec![8, 1, 16, 1, 24, 1, 32, 1, 40, 1, 48, 1, 56, 1, 64, 1, 72, 1, 80, 1];
    let key_type: Vec<u8> = vec![42, 0];

    println!("hash is_valid: {}", Hash::is_valid(hash));
    println!("hash: {:?}", Hash::from_i32(hash));

    println!("usage_flags: {:?}", UsageFlags::decode(&*usage_flags));
    println!("key_type: {:?}", KeyType::decode(&*key_type));
```

Result:
```
hash is_valid: true
hash: Some(Sha3512)
usage_flags: Ok(UsageFlags { export: true, copy: true, cache: true, encrypt: true, decrypt: true, sign_message: true, verify_message: true, sign_hash: true, verify_hash: true, derive: true, touste: false })
key_type: Ok(KeyType { variant: Some(Des(Des)) })
```

Everything works as expected and also notice that the `touste` field was set to its default value. That maps with [the documentation](https://developers.google.com/protocol-buffers/docs/proto3#default).

## Deserialize new data with old version

Test file:
```rust
// Generate buffers for Hash, KeyType, UsageFlags
#[test]
fn touste() {
    use psa_key_attributes::{UsageFlags, KeyType};
    use psa_algorithm::algorithm::Hash;
    use prost::Message;

    let hash: i32 = 16;
    let usage_flags: Vec<u8> = vec![8, 1, 16, 1, 24, 1, 32, 1, 40, 1, 48, 1, 56, 1, 64, 1, 72, 1, 80, 1, 88, 1];
    let key_type: Vec<u8> = vec![122, 0];

    println!("hash is_valid: {}", Hash::is_valid(hash));
    println!("hash: {:?}", Hash::from_i32(hash));

    println!("usage_flags: {:?}", UsageFlags::decode(&*usage_flags));
    println!("key_type: {:?}", KeyType::decode(&*key_type));
```

Result:
```
hash is_valid: false
hash: None
usage_flags: Ok(UsageFlags { export: true, copy: true, cache: true, encrypt: true, decrypt: true, sign_message: true, verify_message: true, sign_hash: true, verify_hash: true, derive: true })
key_type: Ok(KeyType { variant: None })
```

The hash is not recognised as valid. The `UsageFlags` parsing worked and the `touste` field was ignored. The `KeyType` parsing worked (as in no encoding error) but the variant is not recognised. That maps [with the documentation](https://developers.google.com/protocol-buffers/docs/proto3#backwards-compatibility_issues):

> Be careful when adding or removing oneof fields. If checking the value of a oneof returns None/NOT_SET, it could mean that the oneof has not been set or it has been set to a field in a different version of the oneof. There is no way to tell the difference, since there's no way to know if an unknown field on the wire is a member of the oneof.

# Analysis

Note that part of the decision taken here is also valid for #394 if we decide to store the protobuf format of the key mappings instead of the Serde one. Will assume that in the following.

The old/new versions of the test data/parsec interface will represent communication between different versions of the Parsec service/Parsec client or different versions between the Parsec service and the key mappings.

As shown here, one direction (sending old data to a new interface) is fine: old enumerated types can still be recognised and new fields are set to their default values. For new fields of messages though, it means that they **must** be optional, with the same default value as protobuf. If not set, the contract should have exactly the same behaviour as the old version.

The other direction (sending new data to an old interface) is more problematic. Let's see the different cases.

## The Parsec service is newer than the client

All requests would be understood correctly by the service. Behaviour of operations would be the same.

Responses from the service to the client that contain new variants of enumerated types won't be able to be deserialised. For example, if a key with a new hash algorithm is created by one new client and tried to be read (ie `ListKeys`) by an old client, the old client would have to either return an error for this specific key, or replace the algorithm with a placeholder ("not supported", "unknown", etc). If it returns an error, it should be different one than a failed encoding, ie `PsaErrorNotSupported`.
Note that this case would also happen for an unrecognised `ResponseStatus`.

Responses from the service to the client that contain new message fields will be deserialised successfully but the fields ignored. Clients might then not know that the key has some different behaviour than what they expect.

## The Parsec service is newer than its stored mappings

Everything is fine.

## The Parsec service is older than the client

Some requests (enumerated types) will not be deserializable and will return `PsaErrorNotSupported` or equivalent. The client will not be able to know exactly what was not supported unless they check the logs or use other mechanism (not yet implemented) for discovery of allowed parameters/capabilities.
The requests with the new message fields will work but the fields will be ignored. It means that some behaviour of the request will be ignored by the service unless the client knows about it.

## The Parsec service is older than its stored mappings

The mappings might not be readable, unless the enumerated types are replaced with a "default" or a "placeholder" value. Not possible if you actually need to use the key (as opposed as just reading its information).

# Decision options

I see the following options:

1. Stick with version 1.0.0 of PSA Crypto and only import bug fixes on the interface (like update to the documentation of operations/types). Create a `1.0.0` feature on the `psa-crypto` crate and use that in Parsec. From that point, if there is a new non-breaking feature in PSA Crypto we can:
  1. Use the other 2 option
  2. Use the open-close principle strictly: create new versions of everything that needs an update.
2. Allow non-breaking changes (or restrict them to a subset):
  1. New message fields should be optional. The behaviour of the operation should be the same if not set/not supported by the interface. Those fields would be "best-effort": their behaviour is applied is supported but ignored if not.
  2. New enumerated values might trigger `PsaErrorNotSupported` in the interface. A new discovery operation to check allowed values on the interface might be needed. Note that a value can be allowed on the interface but unsupported by the provider.
  3. If Parsec is replaced with an older version, the mappings might not be readable. This might be fine as we do not cover rollback stability for persistent storage.
  
1 seems easier to manage with what we have currently and helps with general stability. Different versions of clients-services will always work with less out-of-band processes. There will be some work required to maintain the `1.0.0` feature of `psa-crypto` but that's manageable.
2 will need a bit more work in the interface to make sure the correct error is returned. A new operation will have to be designed. Clients will have to be smarter to handle those cases. That however allows easier scaling and less duplication.

How soon will we need to update our interfaces? The only things added so far is a new hash alg (SM3) and a new key type (SM4). Are they needed/requested immediately? Will there be any PSA Crypto features released soon that will be needed in Parsec? It's not scalable to create new version of everything every PSA Crypto update.

My personal opinion is that, if we don't plan to use any new PSA Crypto feature anytime soon, we should go for 1.

**Comment by hug-dev** [comment]
# More details about testing

There are two directions to test:

- We should have a set of test (maybe one per operation?) in different versions of different clients done on each PR/`main` branch. I propose to test the last three relevant versions of each client.
- We should also make sure that old versions of Parsec still work with new changes on the clients. Similarly, we can test that the three last relevent Parsec versions work with the latest `main` branch of the clients. This can be done either `nightly` on Parsec or on each PR of the clients (maybe better).

The same tests can probably be used for the two things above.

**Comment by ionut-arm** [comment]
> Testing should be composed of a various set of operations using different parameters with different versions of the Rust clients against different versions of the Parsec service.

I don't think that's necessary - if you always test against the oldest supported version, you can be sure that all the intermediary versions (until the current one) are also consistent with it, so there's no need to test against them. So we can check oldest client -> newest service and newest client -> oldest service, that should cover everything.

**Comment by hug-dev** [comment]
> The Parsec service is older than its stored mappings

Note that we don't have to cover this case as Parsec will not be stable for service rollbacks.

**Comment by hug-dev** [comment]
I thought about how to achieve some kind of service discovery for the case where the client is newer than the service so that it can check what operation it can do. More than just limiting to what *interface* it can use (the one of the version of the service), it would be nice if the discovery operations inform on what is supported on each provider.
It would solve the problem for clients to only request operations that are supported and in the future, do some kind of automatic optimization to find the best algorithm to use.

For the case where the service is newer than the client, the only problem is if the responses contain fields/variants that the client does not know. I think those issues can be adressed separately on the specific operations they can appear on. The only one I see so far is if the `KeyAttributes` is upgraded as it is in the `ListKeys` response. That specific operation should show something like "unkown" on the specific keys which attributes it can not deserialize. Or not show the attributes of that key but just its name if possible. This problem will be solved on a case-by-case basis.

Now the problem is reduced to: "what are the supported parameters for this operation on this provider?"

This can be refined for each specific field of each operation. However some fields like `key_name` (String) can have any value so a finite list of possible values could not be given. Also some operations take vector of bytes which could have any value. The only fields which have a discrete set of supported values are:
- for key generation/import: the possible [`KeyAttributes`](https://parallaxsecond.github.io/parsec-book/parsec_client/operations/psa_key_attributes.html#keyattributes-type) values. Note that different attributes are supported for generation and import.
- for crypto operations: the supported [algorithms](https://parallaxsecond.github.io/parsec-book/parsec_client/operations/psa_algorithm.html#algorithm-type)

I then propose to add three new operations:
1. GetSupportedAlgorithms
2. GetSupportedKeyAttributes

They would be non-core operations (directed at crypto providers). They could be core operation with a `provider_id` parameter as well.

# GetSupportedAlgorithms

Get a set of supported algorithms by the provider. Opcode: 30 (`0x001D`)

## Parameters

No parameters are needed for this operation.

## Results

| Name        | Type            | Description                     |
|-------------|-----------------|---------------------------------|
| `algorithms` | Vector of Algorithm | Vector of supported Algorithm values |

## Specific response status codes

No specific response status codes returned.

## Description

This operation returns the algorithms supported by the provider. The exact values returned can be used directly on the specific operations where they are needed.

# GetSupportedKeyAttributes

Get a set of supported key attributes for generation or import by the provider. Opcode: 31 (`0x001E`)

## Parameters

| Name   | Type                                 | Description             |
|--------|--------------------------------------|-------------------------|
| `creation_type` | KeyCreationType | Type of the key creation |

### KeyCreationType type

A `KeyCreationType` type can contain one of the following:

- **Generation**
- **Import**

## Results

| Name        | Type            | Description                     |
|-------------|-----------------|---------------------------------|
| `attributes` | Vector of KeyAttributes | Vector of supported KeyAttributes values |

## Specific response status codes

No specific response status codes returned.

## Description

This operation returns the key attributes supported for generation or import by the provider. The exact values returned can be used directly when generating or importing keys.

In the `KeyAttributes` values returned, the `key_policy` field is not relevent and should not be used. The necessary usage flags and permitted algorithms should be set independantly per key. The `key_usage_flags` field will be set with all its fields to `false` and the `key_algorithm` field will be set to `None`.

**Comment by hug-dev** [comment]
During the community meeting it was noted that:
- following non-breaking changes are fine but we should make sure that the correct errors are returned
- new fields added must be optional, the default value set by protobuf should yield to the same behaviour as without the field
- tools should be added on the contracts to check for breaking changes
- the capability discovery operations are not strictly needed for a baseline stability and should not be prioritised now (only the above points)

**Comment by hug-dev** [comment]
The [open-close principle](https://parallaxsecond.github.io/parsec-book/parsec_client/api_overview.html#open-closed-principle) paragraph will have to be updated to say that non-breaking changes are possible.
