### ISSUE TITLE
Set up Github security policy

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#398]
Disclosure of security issues should happen through a safe channel, and Github allows us to set up a policy for such disclosures. The exact content of the policy and the contact point should be decided under this issue. 

We should look up other CNCF projects and take not of how they deal with this. [Spire](https://github.com/spiffe/spire/security/policy), for example, keeps track of the versions which are still supported for security updates.

Ideally, all repos that have some significant complexity and are not intended for testing should have a security policy.

**Comment by ionut-arm** [comment]
Proposed policy:

-----

# Security policy

Security is of paramount importance to the Parsec project. We do all we can to identify and fix issues, however some problems might slip through the cracks. Any efforts towards responsible disclosure of security problems are greatly appreciated and your contributions will be acknowledged.

## Supported versions

Currently only the most recent version of the Parsec service is eligible for patching. This could change once a first stable version (`1.0.0`) is reached.

| Version                 | Supported |
| ------------------ | ----------- |
| 0.7.0                     | ✅            |
| 0.6.0 and lower     | ❌            |

## Reporting a vulnerability

To report a vulnerability, please send an email to [cncf-parsec-maintainers@lists.cncf.io](mailto:cncf-parsec-maintainers@lists.cncf.io). We will reply to acknowledge your report and we'll strive to keep you in the loop as we try to reach a resolution.

Any reports that are deemed of valid concern will be released as a security advisory.

**Comment by hug-dev** [comment]
I like the idea of maintaining the security of multiple supported versions of Parsec! We could say something like "the last 3 major version numbers are maintained for security"?

Note that this relates with the discussion we'll have on our roadmap/release strategy. If we maintain multiple versions in parallel, we'll need to have multiple actual `git` branches where we can apply security fixes.

Also, here we are talking of security but the supported versions could also be for bug fixes!

**Comment by ionut-arm** [comment]
Yeah, I just don't know what to say right now because we don't have stable releases yet, so "last 3 major version numbers" doesn't really mean much :grin: And if we go beyond 0.6.0 as supported version, it's going to be quite "old".

Should we discuss this in the next community meeting? It's somewhat related to release schedules as well.
