### ISSUE TITLE
Stability: Environment variables

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#405]
Definition: Environment variables should still have the same behaviour in future stable Parsec versions.
Enforcement: Env var behaviours must not be removed in Parsec.

# Enforcement Check

Environment variables can be used to modify the buildtime/runtime configuration of Parsec. For example currently the `psa-crypto` crates reads for `MBEDTLS_LIB_DIR`, `MBEDTLS_INCLUDE_DIR` and `MBEDCRYPTO_STATIC` variables. Parsec builders might depend on these variable to still work.

Parsec can not really enforce it as some env var might be read by other crates. We should however identify the important ones and make sure they still work in the future.

This can only be checked via testing/code review.

# Testing

For testing, those env vars should be exerced for different versions of Parsec.

**Comment by ionut-arm** [comment]
Worth including the `PKG_CONFIG` variables here, needed in some cases for cross-compilation. Some details about cross compilation with `pkg-config` [here](https://autotools.io/pkgconfig/cross-compiling.html), and some Rust-specific stuff [here](https://docs.rs/pkg-config/0.3.19/pkg_config/)

**Comment by hug-dev** [comment]
We can not possibly track all environment variables used in all the dependency tree but we can list and test the ones we define and are important in Parsec:

- `MBEDTLS_INCLUDE_DIR`: location of the PSA Crypto header files (defined [here](https://github.com/parallaxsecond/rust-psa-crypto/tree/main/psa-crypto-sys))
- `MBEDTLS_LIB_DIR`: location of the PSA Crypto library (`libmbedcrypto.a/so`)
- `MBEDCRYPTO_STATIC`: flag to enable static compilation to Mbed Crypto

The first two variables are tested in the [CI script](https://github.com/parallaxsecond/parsec/blob/b940fa0c4df2158646a424c06284015b72f88a49/ci.sh#L176). The last one is tested in the [`psa-crypto` CI](https://github.com/parallaxsecond/rust-psa-crypto/blob/8605006d34944fa880edd3d4d347f460c5585747/ci.sh#L71).
