### ISSUE TITLE
Stability: Build toolchain

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#408]
Definition: Parsec build should not break for defined versions of the Rust compiler
Enforcement: Each commit is tested with specific supported versions of the Rust compiler.

# Enforcement Check

We could adopt the same process as in the [`tss-esapi`](https://github.com/parallaxsecond/rust-tss-esapi#minimum-supported-rust-version-msrv) crate where some versions of Rust are used to build:
- the latest `stable`
- the most recent one in Fedora
- we can get request to add requirement for more

This could be enforced in our various repos as well to catch build failures earlier.

# Testing

Regular CI tests

**Comment by ionut-arm** [comment]
What about `clippy`/linting issues? I think we should reserve the right to break/ignore new lint rules indefinitely. This is particularly important if we want to maintain multiple versions in parallel (see that latest clippy lints complaining about naming rules).

**Comment by hug-dev** [comment]
> I think we should reserve the right to break/ignore new lint rules indefinitely.

Yes I think so too, ultimately `clippy` only helps us writing better code but that should be fine if we ignore some rules if they break other stability rules.

**Comment by hug-dev** [comment]
Reminder that this need to be added in the book as well.

**Comment by hug-dev** [comment]
Also thinking that the `--features` flag should have the same behaviour than the CLI options: they should not change in a breaking way.
