### ISSUE TITLE
Support ECC signing keys in the PKCS#11 provider

### ISSUE THREAD

**Issue by paulhowardarm** [parallaxsecond/parsec#421]
### Summary
Add ECC signing key support to the PKCS#11 provider for feature parity with TPM, Mbed, Trusted Service and CryptoAuthLib providers.

### Details
ECC keys to be supported by the following API operations

- `PsaImportKey`
- `PsaGenerateKey`
- `PsaDestroyKey`
- `PsaExportPublicKey`
- `PsaSignHash`
- `PsaVerifyHash`

Curve family support may be subject to some restrictions - aim for feature parity with TPM 2.0 for now.

**Comment by ionut-arm** [comment]
#446 covered the following:

* `PsaGenerateKey`
* `PsaDestroyKey`
* `PsaSignHash`
* `PsaVerifyHash`

The other two will be done in a new PR along with any changes to the shims that allow the (public key) operations to be passed to Mbed Crypto if missing

**Comment by ionut-arm** [comment]
#452 covered:

* `PsaImportKey`
* `PsaExportPublicKey`
* fixing some bugs in sign and verify
* testing on the Nitrokey HSM

Support for ECC keys should now be fully available, at least at the same level as the TPM provider, mostly aimed at SECP R1 curves.
