### ISSUE TITLE
Add version structures for better handling of versions

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#43]
Service/protocol versions are used in request/response headers and in the ping operation.

At the moment these values are stored as two separate integers. It would be helpful if:
* They were represented by a `Version` object
* We had an explicit agreement on how to handle a difference between the version of a backend handler and the version specified in a request header handled by it.

**Comment by hug-dev** [comment]
Please see #105 for more information on versioning.

**Comment by hug-dev** [comment]
The second point of this issue has been adressed by #105. Renaming it "Add a Version objects" to handle the replacement of our minor/major/rev versions by those richer structures.

**Comment by ionut-arm** [comment]
Part of this was solved by https://github.com/parallaxsecond/parsec-interface-rs/issues/41 . But we do need to figure out the bigger picture of handling different wire protocol versions within the client and the service.

**Comment by hug-dev** [comment]
The big picture of version handling should be adressed by #169
