### ISSUE TITLE
Switch to dynamic key names in tests

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#453]
Almost all our E2E tests need to deal with keys, and most use the same default client name, meaning that all keys are created in the same namespace. Since we want the tests to be quick and to also test the parallelism of the service, we run them in parallel threads. These points together mean that we need to preserve independent names for the keys used in most tests so that they don't end up stepping on each other's toes. This is currently achieved by giving the key name the same value as the test name, statically:

https://github.com/parallaxsecond/parsec/blob/094f8c119446fa778dfc0dbc0af6102003c47cd0/e2e_tests/tests/per_provider/normal_tests/create_destroy_key.rs#L12

It would be much nicer to get this name dynamically so that we don't have to always worry about changing the names when, e.g., duplicating a test to check some other parameters. An idea would be to use [`function_name!`](https://docs.rs/stdext/0.3.0/stdext/macro.function_name.html) from the `stdext` crate. I tried it locally for one test and it seemed to work fine.

**Comment by hug-dev** [comment]
Agree that this would make writing tests easier 👌 
In the same vein, I am thinking if we could introduce/use a function/macro to generate a random key name per test. That way you don't even have to care if you are writing a unique test name.

**Comment by jn9e9** [comment]
@ionut-arm happy to take this on - can you assign to me or shall i just do and create PR?

**Comment by ionut-arm** [comment]
Ah, nice, thanks for offering to look at this! Just a heads up (actually mostly for @anta5010 for now) that there are two outstanding "branches" in the repo that contain features intended for the next release and which touch on the tests as well. I think we'll fix conflicts when we intend to merge those branches back in `main` :)
