### ISSUE TITLE
Refactor the all-providers workflow

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#455]
The all-providers CI workflow has spiralled into a 40min test run. This has happened quite suddenly over the last few weeks when a number of tests and checks were added. It would be good to split the workflow up and reduce the overhead of a CI run.

My current breakdown of what's going on (taken from [here](https://pipelines.actions.githubusercontent.com/2ZNCxk45Rk6uVwnBrnYsthAHCmmVla7B9t08MdHq3mMR0b6ttL/_apis/pipelines/1/runs/1352/signedlogcontent/11?urlExpires=2021-06-29T10%3A43%3A39.4126785Z&urlSigningMethod=HMACV1&urlSignature=DFTm9zy4q%2BBz5BBMiWdoQ6zjIFfoLDJUEs2FAI8AQ0E%3D)) is:
* Build test - 20 mins
* Unit tests + start service - 3 mins
* All-providers normal tests - 5 mins
* Multi-tenancy tests - 10 mins
* Config tests - 1 min

Build tests definitely need to be split into a different workflow, and given that they take roughly as much as the others combined, there's probably not much point in splitting those at this point.

**Comment by hug-dev** [comment]
Probably linked with #447

**Comment by ionut-arm** [comment]
Ah, fair, I forgot we had an issue for that! Well, closing this and we can just do it under #447.
