### ISSUE TITLE
Investigate the strange CodeCov reports

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#460]
Code coverage reporting was out of order for a while, and now that it's working again, the numbers are somewhat strange. You can see the most recent report [here](https://app.codecov.io/gh/parallaxsecond/parsec). The coverage has dropped, despite us adding new tests for various bits of functionality, while some parts of the report are nonsensical. For example, in [this](https://codecov.io/gh/parallaxsecond/parsec/src/2af44cc6dc10b23511e9442f4281636728c59a14/src/providers/tpm/key_management.rs) report of the key management functionality of the TPM provider, there are a number of inconsistent or illogical results:
* The first line in a few functions is shown as uncovered, even though there is no branching involved and other lines in those functions are covered
* The last line in a few functions is shown as uncovered, even though we have hundreds of tests that use those functions and rely on them touching that line (e.g. line 237, which marks a successful key deletion)
* Other lines that are shown as uncovered even though they must have happened for others after them to also be covered (e.g. lines 169-170, which are covered in a [previous report](https://codecov.io/gh/parallaxsecond/parsec/src/b6b73160498e52cbfb3527f5120036c729f91920/src/providers/tpm/key_management.rs))

There is a need to investigate why those inconsistencies suddenly appeared - maybe some of the recent changes in the `ci.sh` file have lead to this, or changes in the Rust compiler...?

More tests might also be needed, but these problems seem to stem from external issues - we've not been actually losing coverage, we just hit some tooling errors.

**Comment by ionut-arm** [comment]
It seems this was reported previously by someone else: https://github.com/xd009642/tarpaulin/issues/757 So I'm tempted to revert to 0.16.0

**Comment by hug-dev** [comment]
Yeah I think it's worth to try and test the coverage generated to see if it changes anything
