### ISSUE TITLE
Recognise a PKCS11 hardware token with its serial number instead of slot number

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#481]
To interface with a specific PKCS11 implementation token, Parsec currently uses the slot number (`CK_SLOT_ID`) of the token.

As stated [here](https://github.com/parallaxsecond/parsec/issues/404#issuecomment-858634017) and [here](https://github.com/Yubico/yubico-piv-tool/issues/312#issuecomment-882483482) this is a bit fragile:
- the slot number can change if the device is unplugged and re-plugged
- the slot number can map to a different device if a different device is plugged-in instead
- the slot number can change if the OS is rebooted

Ideally, the admin would know the serial number of the device they want to use with Parsec and enter that + its PIN in the configuration file. That way, the slot number might change the same device will always be used with Parsec.

Parsec configuration is stable. That means that we can not remove support for the `slot_number` field. Instead we can do:
- if no `slot_number` or `serial_number` is entered *and* there is only one slot available, use that one (#375)
- if only `slot_number` is entered, check that the slot number is valid via `GetSlotList` and use that one. Print a warning message that slot number might change and that serial number is preferred.
- if only `serial_number` is entered, call `GetSlotList` then `GetTokenInfo` for each one of them and use the slot ID mapping with the serial number
- if both are entered, use the `serial_number` logic

About security: as per our [threat model](https://parallaxsecond.github.io/parsec-book/parsec_security/parsec_threat_model/threat_model.html), the admin and what they write in the configuration file is trusted. The machine is not supposed to be accessed physically by untrusted agents. For those reasons I don't recognise this as a security issue.

**Comment by mohamedasaker-arm** [comment]
Is it helpful to add a warning when there is a mismatch between the  `slot_number` provided and the actual  ` slot_number` of the given token?
for example:
Token T with sn: 0 is at slot 1
in config:
`serial_number` = 0
`slot_number` = 2

**Comment by hug-dev** [comment]
Hey!
Thanks for tackling this issue :smiley: 

If both `serial_number` and `slot_number` are written in the config, I would say that it would be nice to print a warning saying that the `slot_number` is ignored and can be removed from it. But I don't think that it's necessary to check that the `slot_number` does not match

**Comment by ionut-arm** [comment]
Hmm, not sure. I agree on the warning message, but I'd lean towards stopping the service because something ain't right. My reason being that perhaps they wrote down the wrong serial number and it's the slot number that's correct. I guess it would fail at the first login, since the PIN would be incorrect, but it still seems weird to continue if you have the configuration clearly wrong somewhere.

**Comment by ionut-arm** [comment]
I'm happy either way - it's more friendly towards admins if we just log a warning and proceed with the mismatching serial/slot numbers, but it might bite them later on. Feel free to either error out or not! Don't think we have a strict stance on this.
