### ISSUE TITLE
Fuzz Testing & Nightly Cargo udeps are failing due to prost-derive

### ISSUE THREAD

**Issue by MattDavis00** [parallaxsecond/parsec#514]
As mentioned, Fuzz Testing & Nightly Cargo udeps are failing due to prost-derive.

```
   Compiling prost-derive v0.6.1
error[E0034]: multiple applicable items in scope
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-derive-0.6.1/src/lib.rs:111:14
    |
111 |             .intersperse(quote!(|));
    |              ^^^^^^^^^^^ multiple `intersperse` found
    |
    = note: candidate #1 is defined in an impl of the trait `Iterator` for the type `Map<I, F>`
    = note: candidate #2 is defined in an impl of the trait `Itertools` for the type `T`
help: disambiguate the associated function for candidate #1
    |
107 ~         let tags = Iterator::intersperse(field
108 +             .tags()
109 +             .into_iter()
110 +             .map(|tag| quote!(#tag)), {
111 +         let mut _s = $crate::__private::TokenStream::new();
112 +         $crate::quote_each_token!(_s $($tt)*);
  ...
help: disambiguate the associated function for candidate #2
    |
107 ~         let tags = Itertools::intersperse(field
108 +             .tags()
109 +             .into_iter()
110 +             .map(|tag| quote!(#tag)), {
111 +         let mut _s = $crate::__private::TokenStream::new();
112 +         $crate::quote_each_token!(_s $($tt)*);
```

**Comment by MattDavis00** [comment]
Parsec interface is running `0.6.1` and Parsec service is running `0.7.0`.
An attempt at updating `prost` & `prost-build` within the Parsec interface does not seem to fix the issue as seen [here](https://github.com/MattDavis00/parsec/runs/3507748909)

**Comment by MattDavis00** [comment]
Seems to be related to https://github.com/rust-lang/rust/issues/88878

**Comment by MattDavis00** [comment]
Seems to have been picked up within the `prost` crate here https://github.com/tokio-rs/prost/issues/526
Looks like the fix is either **pin the nightly builds to an older version** or **update `prost` to `0.8.0`**

**Comment by MattDavis00** [comment]
Updating prost to `0.8.0` seems to fix the Itertools `.intersperse()` conflict. It however raises some additional errors:
https://github.com/MattDavis00/parsec/actions/runs/1233575094
https://github.com/MattDavis00/parsec/actions/runs/1233578406

**Comment by ionut-arm** [comment]
Those ones are fixed if you do a `cargo update`, I think, but the bigger problem is that we can't update `prost` for now because it conflicts with our Minimum Rust Supported Version, see https://github.com/parallaxsecond/parsec/pull/471

I've added this as a discussion point for today's meeting.

**Comment by hug-dev** [comment]
Hey @ggardet!
Small question. Reading from the `rust.spec` file of this [page](https://build.opensuse.org/package/show/openSUSE:Leap:15.3:Update/rust) (you linked when I asked you in a previous issue), can we assume that Leap 15.3 is now using Rust version 1.53.0? If that's the case, can we update our CI scripts to use that as our Minimum Rust Supported Version?

**Comment by ggardet** [comment]
> Hey @ggardet!
> Small question. Reading from the `rust.spec` file of this [page](https://build.opensuse.org/package/show/openSUSE:Leap:15.3:Update/rust) (you linked when I asked you in a previous issue), can we assume that Leap 15.3 is now using Rust version 1.53.0? If that's the case, can we update our CI scripts to use that as our Minimum Rust Supported Version?

Indeed, rust 1.53 is now available from the update channel. So, you should be able to bump the min version safely.
