### ISSUE TITLE
Create stability tests for SQLite KIM

### ISSUE THREAD

**Issue by MattDavis00** [parallaxsecond/parsec#519]
Once the first release of the `SQLiteKeyInfoManager` has been made, we should have some tests to ensure that the KIM matches our stability requirements.

This can be similar to the testing performed here:
1. [Generate keys with old version of Parsec](https://github.com/parallaxsecond/parsec/blob/main/e2e_tests/docker_image/generate-keys.sh)
2. [Test they are still valid and functional with the new version](https://github.com/parallaxsecond/parsec/blob/main/e2e_tests/tests/per_provider/key_mappings.rs)

In essence; this testing should ensure that a `SQLiteKIM` database, created with the first release of the `SQLiteKIM`, is still valid and functional in every future release of Parsec.

**Comment by ionut-arm** [comment]
Removing this from the 0.9.0 release as the steps need to be taken to implemente the tests after that release stabilizes.
