### ISSUE TITLE
Stable 0.8.1 release depends on tss-esapi alpha 

### ISSUE THREAD

**Issue by nullr0ute** [parallaxsecond/parsec#527]
Is there an active reason to require a alpha of tss-esapi for the 0.8.1 stable release of parsec?

````
Problem: nothing provides requested (crate(tss-esapi/default) >= 7.0.0~alpha.1 with crate(tss-esapi/default) < 8.0.0~)
````

**Comment by hug-dev** [comment]
Asked in the linked issue above. Does that mean that you can't fetch any `alpha` version in your build system?

**Comment by nullr0ute** [comment]
I wouldn't expect a minor stable dot release of something to move to a major alpha release of a dependency, that generally indicates new features rather than bug fix, which probably should be happening on the main branch for the 0.9.x feature release of parsec.

**Comment by nullr0ute** [comment]
Is there a bug fix or something critical in tss-esapi that warrants the bug in requirements there?

**Comment by MattDavis00** [comment]
There is a bug fix for https://github.com/parallaxsecond/parsec/issues/504 (TPM Provider does not persist generated keys across reboot). The fix required changes in the `rust-tss-esapi` crate and Parsec. I believe the `rust-tss-esapi` PR made breaking changes as part of the fix, hence the major version change. The new Parsec version uses this new version of `rust-tss-esapi` is to consume some of the fixes for the TPM issue, no new features have been added to Parsec. Hopefully this answers some of your questions, if not @ionut-arm (contributor for the PRs) or @hug-dev are likely your best points of contact.

Relevant PRs:
Parsec: https://github.com/parallaxsecond/parsec/pull/515
rust-tss-esapi: https://github.com/parallaxsecond/rust-tss-esapi/pull/256
