### ISSUE TITLE
Update the Parsec Book to include SQLiteKeyInfoManager

### ISSUE THREAD

**Issue by MattDavis00** [parallaxsecond/parsec#532]
Todo:
- [ ] Update the Key Info Manager [page](https://parallaxsecond.github.io/parsec-book/parsec_service/key_info_managers.html?highlight=KIM#key-info-managers) to include the SQLiteKIM.
- [ ] Add any appropriate additional items to the [security model](https://parallaxsecond.github.io/parsec-book/parsec_security/parsec_threat_model/threat_model.html).
- [ ] Rename mentions of Key Triples to Key Identities.

**Comment by ionut-arm** [comment]
This was done in https://github.com/parallaxsecond/parsec-book/pull/141
