### ISSUE TITLE
Add cross-compilation to Aarch64 logic and investigate CI testing

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#55]
Currently all tests in our CI execute on x86.
We need to make sure that compiling the service is as easy as `cargo build --target aarch64-unknown-linux-gnu`. It will be currently except for the compilation of Mbed Crypto which needs extra logic in `build.rs` scripts.
We also need to investigate CI testing on this target and what are our options.
We can look at [cross](https://crates.io/crates/cross) and at [native testing using Travis](https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support).

**Comment by hug-dev** [comment]
To cross-compile before, it used to be as easy as changing the Mbed Crypto library compiler in the `build-conf.toml` file and do the command: `cargo build --target aarch64-unknown-linux-gnu`
But with that now the compilation fails with the following issue:
```
          /usr/bin/ld: /home/hugdev01/dev/parsec/parsec/target/aarch64-unknown-linux-gnu/debug/deps/parsec-b832778a0064e80a.103gqkamrymphzyu.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/hugdev01/dev/parsec/parsec/target/aarch64-unknown-linux-gnu/debug/deps/parsec-b832778a0064e80a.103gqkamrymphzyu.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/hugdev01/dev/parsec/parsec/target/aarch64-unknown-linux-gnu/debug/deps/parsec-b832778a0064e80a.103gqkamrymphzyu.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/hugdev01/dev/parsec/parsec/target/aarch64-unknown-linux-gnu/debug/deps/parsec-b832778a0064e80a.103gqkamrymphzyu.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/hugdev01/dev/parsec/parsec/target/aarch64-unknown-linux-gnu/debug/deps/parsec-b832778a0064e80a.103gqkamrymphzyu.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/hugdev01/dev/parsec/parsec/target/aarch64-unknown-linux-gnu/debug/deps/parsec-b832778a0064e80a.103gqkamrymphzyu.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/hugdev01/dev/parsec/parsec/target/aarch64-unknown-linux-gnu/debug/deps/parsec-b832778a0064e80a.103gqkamrymphzyu.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/hugdev01/dev/parsec/parsec/target/aarch64-unknown-linux-gnu/debug/deps/parsec-b832778a0064e80a.103gqkamrymphzyu.rcgu.o: error adding symbols: file in wrong format
          collect2: error: ld returned 1 exit status
```
It might be because the linker used is the system linker and not an Aarch64-toolchain linker?

**Comment by adamparco** [comment]
You could also leverage buildx to do emulated builds, or to point to a remote armv8 builder instance (AWS A1).

**Comment by hug-dev** [comment]
Part of this issue is being addressed in #61: `cargo build --target aarch64-unknown-linux-gnu` will now cross-compile everything to this target.
To fix the issue above, the linker is precised in `.cargo/config`. I thought that the linker shipped with Rust installation could be used as well for cross-compiling but I think it does not support this target (or is not included?).

The remaining parts of this issue are related with **testing**:
- [ ] adding a CI job that cross-compile PARSEC for the Arm64 target (maybe buildx or [cross](https://github.com/rust-embedded/cross) could be used here)
- [ ] adding CI system where some of the tests are compiled and executed natively on Arm64 (Travis CI, AWS A1, Codefresh can be looked at)

**Comment by hug-dev** [comment]
#64 completed the first point above

**Comment by hug-dev** [comment]
We are going to set up a GitHub Actions self-hosted runner on an Arm Machine! That way we will only need little modification to our GH Actions workflows to make them run on Arm as well.

cf WorksOnArm/cluster#190

**Comment by hug-dev** [comment]
Due to security problems about using [GitHub Actions self-hosted runners](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories), we decided to switch to Travis CI which has been enabled in #90
