### ISSUE TITLE
Add key persistence tests for TS provider

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#568]
As part of the key persistence tests meant to verify that old mappings created by the on-disk KIM are still valid under a current built of the Parsec service, we create keys for different providers using the on-disk KIM using [this](https://github.com/parallaxsecond/parsec/blob/main/e2e_tests/docker_image/generate-keys.sh) script and copying them across when actually running the CI. The CI then runs a number of checks for the providers that have support for such keys, to verify that the correct keys are still visible and usable.

One issue is that the Trusted Service provider [is not included in this testing](https://github.com/parallaxsecond/parsec/blob/main/e2e_tests/docker_image/generate-keys.sh#L43). The main reason was the impossibility of running both the Mbed Crypto provider and the TS provider in parallel in the script linked above (see an explanation [here](https://github.com/parallaxsecond/parsec/pull/566#discussion_r765837789)). However, a solution could be that we clear out the Mbed Crypto keys (`*.psa_its`), restart the system with only the TS provider enabled, generate the keys and copy across the mappings and the key files (again, `*.psa_its`). Since the namespace of the keys would collide with Mbed Crypto, they can be kept in a separate folder for when the TS tests occur.

**Comment by mohamedasaker-arm** [comment]
Hi, I looked into this issue, and I've broken down this work into the following:
- Generate TS keys via an old version of parsec
- [ ] Find an old version of "TS mock" compatible with the old version of parsec.
- [ ] Build the old TS inside the docker
- [ ] Update generate key script to generate the TS keys in a separate folder
- [ ] Build a new version of TS compatible with the latest version of parsec
- Run key mapping test
- [ ] Update the "ci.sh" script to handle the mapping for mbedcrypto and TS  to avoid conflicts

Does the above work cover this issue's scope, or do I miss some?
