### ISSUE TITLE
Drop key handles implicitly

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#57]
We should remove the mental strain of remembering to "release" key slots whenever we finish an operation by using a [finally](https://crates.io/crates/finally-block) closure to do it for us whenever the key handle goes out of scope.

it'd probably work something like:

```
let key_handle = open_key(...);
let _finally = finally( || release_key(key_handle, &self.key_handle_mutex) );
```

**Comment by hug-dev** [comment]
Would we have to use this `_finally` closure everytime a `key_handle` is instanciated? Could we create a new type with a specific drop trait containing the `release_key` code?

**Comment by ionut-arm** [comment]
We could! I was thinking we could've implemented `Drop` on `psa_key_handle_t` but that's not possible (unless we want to inject code in the bindgened file. 

We can create a wrapper type around `psa_key_handle_t`.
