### ISSUE TITLE
RUSTSEC-2022-0013

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#587]
A new vulnerability has been tagged in the `regex` crate (see [here](https://rustsec.org/advisories/RUSTSEC-2022-0013)). For a view of the failing nightly run, please see [the nightly Actions results](https://github.com/parallaxsecond/parsec/actions/workflows/nightly.yml). The suggested mitigation is an update of the version we use in our `Cargo.lock` file. I'll update the thread accordingly.

The vulnerability is still relevant to the 0.8.0 release of Parsec, however, so we need to investigate whether there is any way it can be triggered in any Parsec threads, and potentially create an advisory if so.

**Comment by ionut-arm** [comment]
A quick check in all the crates that report a dependency on `regex` I couldn't find anything taking in an untrusted regex, so I think we're safe from this issue. However, I'd prefer fixing it by forcing `cargo` to update the lock file to use 1.5.5 everywhere. The question is: do we do this for the 1.0.0 release or do we leave it for afterwards?

**Comment by ggardet** [comment]
SUSE is looking for a fix for multiple packages, including `parsec` - https://bugzilla.suse.com/show_bug.cgi?id=1196972

Maybe better to release parsec 1.0.0 without known CVE?

**Comment by ionut-arm** [comment]
Given the discussion around the TSS crate we'll be updating some other things and tagging a third release candidate this week, hopefully, and I'll include a "fix" for the regex issue as well. But just to reaffirm what I said above - based on my visual inspection of the code we don't make have any calls (either in the Parsec service or in our dependencies) to `regex` containing user-provided strings as the expression, which is a requirement of the CVE. I'll do a double-take on that, just to confirm.

**Comment by ionut-arm** [comment]
#592 Fixed this!
