### ISSUE TITLE
Investigate binary bloat

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#597]
The Parsec service and tool binaries have grown considerably between v0.8 and v1.0 - it would be worth investigating what is causing this, and whether we want to do anything about it.

**Comment by paulhowardarm** [comment]
What's "considerably"? Do we have numbers on this?

**Comment by ionut-arm** [comment]
Yes, should've shared in the first post. If you look at the assets shared for both [1.0.0](https://github.com/parallaxsecond/parsec/releases/tag/1.0.0) and [0.8.1](https://github.com/parallaxsecond/parsec/releases/tag/0.8.1) releases (found at the bottom) you can see that the quickstart zipped tarball went from ~4MiB to ~25MiB between the two. The tarball contains the service (compiled with only Mbed Crypto provider, direct authenticator, and peer credential authenticator in both cases) and tool binaries.

The weird part is that now even if I compile the old versions I still get way bigger sizes than before. I'll have to check with older compiler versions, maybe there's a difference :confused:
