### ISSUE TITLE
Wrong permissions on KIM files

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#598]
Both the on-disk and the SQLite KIMs store files on disk, be it individual entries for each key for the on-disk KIM, or one single file representing all the KIM data for the SQLite KIM. The permissions on these files have not been properly locked down, though - at the moment, all such files allow any user capable of reaching the files to read them. This is mitigated by having the files under `/var/lib/parsec`, which does not give any permissions to "other" users, thus preventing anyone other than the `parsec` user and group to access anything within.

Ideally these files (and their host directories) would have similar permissions, though: read and write (and execute, for directories) for the `parsec` user and group.

If possible, a unit test should be implemented to verify the permissions.

**Comment by gowthamsk-arm** [comment]
As stated on this page, https://parallaxsecond.github.io/parsec-book/parsec_service/install_parsec_linux.html
Parsec should be the only user to have access to the KIM files. But the line `the parsec user and group to access anything within` in the issue description suggests a group as well. Do we really need to give access permissions to the group?

**Comment by ionut-arm** [comment]
> Do we really need to give access permissions to the group?

I'm not very knowledgeable about the way users and groups interact - does a new group get automatically created for each user?  If yes, then I'd lean towards "yes, grant access to the group", because other users might be added to that group specifically so they can interact with these files. But if not, then... perhaps not? It's definitely not as critical either way, compared to removing the permissions for "others".

**Comment by mohamedasaker-arm** [comment]
@ionut-arm, Do you have a scenario on top of your head that multiple users need to access these files?
Side-note: I am not against it😸

**Comment by anta5010** [comment]
> Yes, a new group is created with the same user name every time we create a new user.

I don't understand this comment? What do you mean by "we"?
If we're talking about creating user accounts in unix/linux/macos in general then a user own group might and might not be created.

**Comment by ionut-arm** [comment]
> Do you have a scenario on top of your head that multiple users need to access these files?

Any platform running something important would have some accounts for admins, who should be able to work with whatever software is running on the machine. It seems suboptimal to have to log into a different account just to move around or clean up some files. But then again I've never been a sysadmin, so...

> I don't understand this comment? What do you mean by "we"?

I think that was a generic response to a generic question: "when a new user account is created on Unix, is there an associated group created at the same time?" I was/am trying to determine if the group that the service runs under is very likely to be dedicated to Parsec, by default.

**Comment by gowthamsk-arm** [comment]
I was referring to the commands listed on this page.
https://parallaxsecond.github.io/parsec-book/parsec_service/install_parsec_linux.html

**Comment by anta5010** [comment]
> I was referring to the commands listed on this page.
> https://parallaxsecond.github.io/parsec-book/parsec_service/install_parsec_linux.html

On this page we don't create a group for the parsec account. We rely on defaults of the system. It's likely that a new group will be created, but it's not 100%. 

The last sentence is also an answer to Ionut's question: when a new user account is created on Unix, is there an associated group created at the same time?
It depends on what command was used to create an account and what defaults on the system are if any used.
