### ISSUE TITLE
Parsec 1.1 fails to build with meta-security master branch

### ISSUE THREAD

**Issue by anta5010** [parallaxsecond/parsec#663]
On 22.02 tmp2-tss was updated from 3.2.0 to 4.0.1 in meta-security.
https://gitlab.com/akuster/meta-security/-/commit/e188be029cdfdd18f993b0ae2b37d885cfbb191b

Since then Parsec builds fail with:
```
thread 'main' panicked at 'Unsupported TSS version: 4', /home/gitlab-runner/builds/CAxQb6fJ/0/akuster/meta-security/build/tmp/work/cortexa57-poky-linux/parsec-service/1.1.0-r0/cargo_home/bitbake/tss-esapi-7.1.0/build.rs:9:22
```
https://gitlab.com/akuster/meta-security/-/jobs/3818857216

https://github.com/parallaxsecond/rust-tss-esapi/blob/7205c4c825f6d299c7094714d7f5b7dd3fb2b5e9/tss-esapi/build.rs#L9

I can see that it’s fixed in the main branch of tss-esapi:
https://github.com/parallaxsecond/rust-tss-esapi/blob/1a02c8f5be18924bf67a2776f6c5f39dfbe6538a/tss-esapi/build.rs#L13

But, Parsec main branch still uses 7.1.0:
https://github.com/parallaxsecond/parsec/blob/838e93ae5477c3d3ba9223f823b765d8766e0b96/Cargo.toml#L32 (edited)

**Comment by ionut-arm** [comment]
Thanks for reporting this. We should update to `7.2.0` of `tss-esapi` for the upcoming release. `7.2.0` has fixed this already.

**Comment by gowthamsk-arm** [comment]
Thanks for the issue. I will fix it before the release.

**Comment by ggardet** [comment]
I can see this failure on openSUSE Tumbleweed as well.
