### ISSUE TITLE
Parsec Quickstart - Docker: Pull access denied for parallaxsecond/parsec-quickstart, repository does not exist

### ISSUE THREAD

**Issue by sandeepmistry** [parallaxsecond/parsec#666]
Hi,

I'm trying the steps from the ["Parsec Quickstart - Docker" guide](https://github.com/parallaxsecond/parsec/blob/main/quickstart/docker_README.md) and get the following error with running on a Raspberry Pi 4 running Raspberry Pi OS 64-bit.

```
$docker run --rm --name parsec -it parallaxsecond/parsec-quickstart bash
Unable to find image 'parallaxsecond/parsec-quickstart:latest' locally
docker: Error response from daemon: pull access denied for parallaxsecond/parsec-quickstart, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**Comment by gowthamsk-arm** [comment]
Hi @sandeepmistry 
Thank you for raising this issue and apologies for the late response. 
The docker image is now pushed to the registry. 
Can you please use  `ghcr.io/parallaxsecond/parsec-quickstart` in place of `parallaxsecond/parsec-quickstart`?
The document needs to be updated for this.
