### ISSUE TITLE
Migrate away from using users crate

### ISSUE THREAD

**Issue by nullr0ute** [parallaxsecond/parsec#678]
The rust-sec team has recommended moving away from the users crate. The last release of the "users" crate was on 2020-10-08. This is also the last day on which code changes happened in the project's git repo on GitHub.

The "sysinfo" crate is listed as a possible alternative.

RUSTSEC-2023-0040 https://rustsec.org/advisories/RUSTSEC-2023-0040.html

**Comment by tgonzalezorlandoarm** [comment]
#684 resolved this issue, closing.
