### ISSUE TITLE
Test strategy for our providers on the CI

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#69]
I think it could be tested by changing nothing but having a different configuration file which points to the SoftHSM library. There is an available [`Dockerfile`](https://github.com/psmiraglia/docker-softhsm) that installs the library that we can use.

I think we also have to think how we are going to scale testing of multiple providers on the CI.

I was thinking of having single provider tests (our current tests) and multiple providers tests that test more the configuration as opposed to a provider implementation. For that purpose we should have multiple configuration files for all of those cases: one per provider and another one including them all.

**Comment by hug-dev** [comment]
We could add an optional argument when launching Parsec to specify a configuration file path and use this one. That way we can have in-tree one configuration file per provider and test them independently 😄 

And one more with all of them 😈

**Comment by ionut-arm** [comment]
I think we can/should have a CLI option to set the path of the config file for the service and that could also help with tests.

A good way to deal with tests for different provider configurations would be to organize them into folders, place a

**Comment by hug-dev** [comment]
We would have the following test structure (in `tests`):
```
all.sh -> Executing all of the tests below + rustfmt + clippy (will work only if everything is installed)
per_provider/ -> Test executed only with a single provider
    normal/
    stress/
    fuzz/
    persistence/
    PROVIDER_NAME/ -> Folder containing the Dockerfile and config.toml file per provider
        Dockerfile
        config.toml
all_providers/ -> Tests using all providers
    Dockerfile -> Would contain all providers (not published)
    config.toml
    mod.rs
cross_compilation/ -> Testing cross compilation of Parsec
    Dockerfile
    Cross.toml
```

The following `Dockerfile` would be needed:
1. one for the TPM provider + tss-esapi crate (there is one in parallaxsecond/rust-tss-esapi repo already)
2. one for the PKCS 11 provider
3. one for the Mbed Crypto provider + crate (cf #62)
4. one combining 1, 2 and 3 for the `all_providers` tests
5. one for cross-compilation, that already exists

Exactly the same tests (except `cross_compilation`) could be done on an Arm platform, on the CI, check #55 to also have coverage for Arm.
