### ISSUE TITLE
Deny compilation if there is any warning

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#80]
Our code should not compile if there is any warning.

Only this one shoudl be ignored or fix #60

**Comment by hug-dev** [comment]
Not so sure about that one now after reading [this article](https://github.com/rust-unofficial/patterns/blob/master/anti_patterns/deny-warnings.md).
We can still check if compilation on our CI is done without warnings.

**Comment by ionut-arm** [comment]
Would it be ok to use one of the `deny(...)` lists they mention, instead?
