### ISSUE TITLE
Threat model of Parsec

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#89]
After having updated our docs and diagrams we need to threat model Parsec.

**Comment by hug-dev** [comment]
Although the Threat Model has been merged, keeping this for review.

**Comment by hug-dev** [comment]
The Parsec Threat Model can be found at: https://parallaxsecond.github.io/parsec-book/threat_model/threat_model.html

**Comment by RichardAtArm** [comment]
Some notes from our threat model review discussion:
[ReviewOfPARSECThreatModel-200407.txt](https://github.com/parallaxsecond/parsec/files/4445957/ReviewOfPARSECThreatModel-200407.txt)

**Comment by hug-dev** [comment]
On the points raised above:

> It might be helpful to show where data assets are exposed on the data flow diagram.

Agree. We will change that.

> Is the secret Authentication Token the asset that must be protected, rather than the Application Identity, that is not secret?

That is correct! Will rename Application Identity -> Authentication Token

> the Key Mapping store is vulnerable to tampering, as by Attacker – A6 and should be listed as an asset.

That is correct! Should add.

> Mitigation A-3 typo?
> Mitigation A-2 typo?

Well spot! Those should be assumptions, will find another group of letters.

> If some sensitive data is going to be logged to persistent storage, possibly need encrypted file system.

True! We might be safer by checking that we do not log confidential data. I am sure we can log meaningfull information without being too informative.

> In general, it looks like information disclosure from within the process hasn’t been considered. E.g. Auth Token exposed in memory after use.

That is something we thought separately from the TM (in #122). We should definitely add it in the TM in the Information Disclosure attacks.

>  Is the key data stored on-disk protected enough just by OS permissions? Does it need to be encrypted? Protected with HMAC? 

We agree that this is a bit light. We created #118 to start thinking about options. Will add HMAC to the list.

> Are not in the scope of the Threat Model, but could need their own TM to derive general security requirements for clients.

That is a good point, and as we are starting developping the [Rust Client](https://github.com/parallaxsecond/parsec-client-rust), we should also think about creating a threat model for it.

> Make sure the findings of the threat modelling are acted on, e.g. by tracking tasks to: implement the Mitigations; document recommendations for the Operational Mitigations and document the risks and limitations due to the Unmitigations.

Great remark, will do that as soon as the review period for the TM is over.

> it might be helpful to give recommendations or examples for a secure Linux environment:

We will think about adding in our documentation an example of a secure deployment implementing all our operation mitigations.

**Comment by hug-dev** [comment]
Will create issues to address those points as soon as the review period of the TM is over.

**Comment by ionut-arm** [comment]
Created:
* https://github.com/parallaxsecond/parsec-book/issues/33
* https://github.com/parallaxsecond/parsec-book/issues/32
* https://github.com/parallaxsecond/parsec/issues/175

I've also recently updated https://github.com/parallaxsecond/parsec/issues/122 to be in sync with the PSA Crypto spec recommendations.

**Comment by hug-dev** [comment]
Service and Rust client TM have now been updated and published, and the recommendations here have all been adressed.
