### ISSUE TITLE
Check for more Clippy lints

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#91]
The following command:
```bash
cargo clippy --all-targets --all-features -- -D clippy::all -D clippy::pedantic -D clippy::cargo
```
will enable *all* Clippy lints in all Parsec's code.
We should investigate which ones of those should be fixed.

**Comment by hug-dev** [comment]
The same should be done in our other crates.

**Comment by hug-dev** [comment]
All of our operation structures (example: `OpPing`) are declared in their `src/operations/...` (example: `ping.rs`) file.
Clippy, with the `pedantic` lint group enabled complains about that as it is a duplication of name:
```rust
error: item name ends with its containing module's name
  --> src/operations/ping.rs:18:1
   |
18 | pub struct OpPing;
   | ^^^^^^^^^^^^^^^^^^
   |
   = note: `-D clippy::module-name-repetitions` implied by `-D clippy::pedantic`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#module_name_repetitions

error: item name ends with its containing module's name
  --> src/operations/ping.rs:26:1
   |
26 | / pub struct ResultPing {
27 | |     pub supp_version_maj: u8,
28 | |     pub supp_version_min: u8,
29 | | }
   | |_^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#module_name_repetitions
```
The absolute name of the structure is `operations::ping::OpPing` but using namespacing we could rename this structure to be `Operation` only and so its absolute name would be `operations::ping::Operation`
In context where we need to use all the `OpXXX` or all the `ResultXXX`, we can import `operations::{ping, etc}` and use the different ones with `ping::Operation`, `ping::Result`, etc...

What are you thoughts about that?

**Comment by ionut-arm** [comment]
That sounds good! We could eiither use `ping::Operation` or simply re-export them with an alias at the root of the library, i.e. `pub use ...::ping::Operation as OpPing`

**Comment by hug-dev** [comment]
Following the same logic we should also rename all of our Protobuf operations to remove the `PingProto` from `OpPingProto` and `ResultPingProto` (and all of them) as it will be namespaced correctly (to be checked in other languages, like C).
Otherwise we have the same issue:
```rust
use super::generated_ops::ping::{OpPingProto, ResultPingProto};
```
which seems a bit weird if we do not fix as well.
That would incur a lot of changes to leaving that issue for now.

**Comment by hug-dev** [comment]
I will for now add `cargo clippy --all-targets --all-features -- -D clippy::all -D clippy::cargo` to our CIs and create a new issue (out of the `1.0.0` milestone) to add the pedantic one.
